### ISSUE TITLE
seafile cli client init issue

### ISSUE THREAD

**Issue by B3NG** [haiwen/seafile#1054]
Hi,
I've got a problem with the CLI-Client.
I want to run it on a RaspberryPi.
```
pi@RPI / $ uname -a
Linux RPI 3.12.29+ #714 PREEMPT Wed Oct 1 23:11:38 BST 2014 armv6l GNU/Linux
```
I followed the instruction from the manual so far. (https://seacloud.cc/group/3/wiki/seafile-cli-manual/)

When I try to initialize the client I've got an error like this:
```
pi@RPI ~/seafile-cli-4.0.4 $ ./seaf-cli init -d ~/.seafile-client

Traceback (most recent call last):
  File "/home/pi/seafile-cli-4.0.4/bin/seaf-cli.py", line 791, in <module>
    main()
  File "/home/pi/seafile-cli-4.0.4/bin/seaf-cli.py", line 787, in main
    args.func(args)
  File "/home/pi/seafile-cli-4.0.4/bin/seaf-cli.py", line 238, in seaf_init
    if run_argv(cmd, env=get_env()) != 0:
  File "/home/pi/seafile-cli-4.0.4/bin/seaf-cli.py", line 167, in run_argv
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```
I tried it also with the 3.1.5 version - same problem!

Are there some Libs or other requirements missing?

THX 4 your help!

**Comment by shubhank008** [comment]
Make sure you have python installed and its 2.6 or 2.7 ?

**Comment by B3NG** [comment]
Yes, python2.7 and python3.2 are installed.

**Comment by lins05** [comment]
@B3NG Sorry but we don't have an official package of seaf-cli for arm cpu. You need to compile it from source. Check http://manual.seafile.com/build_seafile/server.html

**Comment by B3NG** [comment]
OK, thank you!
