### ISSUE TITLE
Img Preview in Listview (4.0.6)

### ISSUE THREAD

**Issue by githubtobi** [haiwen/seafile#1105]
Hi Dev-Team,
I recently updated from 4.0.1 to 4.0.6 with the minor-update.sh.
But the img-preview in the listview is not working.

Screenshot:
![bildschirmfoto 2015-02-26 um 14 38 07](https://cloud.githubusercontent.com/assets/10399188/6392876/4e116c98-bdc5-11e4-84bf-48594c280137.png)

Seafile is running on a hummingboard with debian, nginx and php-fpm. Do I have to install any other packages?

Best,
Tobi

**Comment by freeplant** [comment]
Any error in your logs/seahub_django_request.log?

**Comment by githubtobi** [comment]
yip:

2015-02-26 20:46:54,181 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/seafile/seafile-server-4.0.6/seahub/seahub/base/middleware.py", line 60, in process_request
    self.get_from_db()
  File "/home/seafile/seafile-server-4.0.6/seahub/seahub/base/middleware.py", line 53, in get_from_db
    refresh_cache()
  File "/home/seafile/seafile-server-4.0.6/seahub/seahub/notifications/utils.py", line 10, in refresh_cache
    NOTIFICATION_CACHE_TIMEOUT)
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/cache/backends/filebased.py", line 65, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 70, in __getstate__
    len(self)
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked

**Comment by githubtobi** [comment]
yip:

2015-02-26 20:46:54,181 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "<seafile-home-dir>/seahub/seahub/base/middleware.py", line 60, in process_request
    self.get_from_db()
  File "<seafile-home-dir>/seahub/seahub/base/middleware.py", line 53, in get_from_db
    refresh_cache()
  File "<seafile-home-dir>/seahub/seahub/notifications/utils.py", line 10, in refresh_cache
    NOTIFICATION_CACHE_TIMEOUT)
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/cache/backends/filebased.py", line 65, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 70, in __getstate__
    len(self)
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "<seafile-home-dir>/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked

**Comment by githubtobi** [comment]
yip:

2015-02-26 20:46:54,181 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/seafile-home-dir/seahub/seahub/base/middleware.py", line 60, in process_request
    self.get_from_db()
  File "/seafile-home-dir/seahub/seahub/base/middleware.py", line 53, in get_from_db
    refresh_cache()
  File "/seafile-home-dir/seahub/seahub/notifications/utils.py", line 10, in refresh_cache
    NOTIFICATION_CACHE_TIMEOUT)
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/core/cache/backends/filebased.py", line 65, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 70, in __getstate__
    len(self)
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/seafile-home-dir/seahub/thirdpart/Django-1.5.1-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
