### ISSUE TITLE
CSV user import error with mac characters

### ISSUE THREAD

**Issue by PJ1004** [haiwen/seafile#1139]
If creating an import csv (email,password) and uploading through the Admin interface -> Import Users, on a Mac, this errors with "Sorry, but the requested page is unavailable due to a server hiccup.  Our engineers have been notified, so check back later."

Seems to be caused by the line endings typical of mac having no carriage return and only a line feed character.

Can the import function be adapted to cater for this?

**Comment by imwhatiam** [comment]
can show us your log files `/path/to/logs/seahub_django_request.log` and `/path/to/logs/seahub.log` here?

we can't reproduce this error.

 and if you put your .csv file here will help more.

**Comment by PJ1004** [comment]
Here's the csv (I can't attach the raw file through this):

<code>
Alice.Moynihan@abc.com,21584819
anne.farmer@abc.com,39961484
avelyn@abc.com,12547533
brionylass@abc.com,37159754
cara.torrance@abc.com,56050455
erica.moffitt@abc.com,40998195
jgabby@abc.com,42936240
edgewind@abc.com,13542595
Blondeoverseas@abc.com,36723246
jrlockyears@abc.com,54876493
Joseph.ong@abc.com,42926671
ken.harrop@abc.com,20108127
kuljit.kaur.nz@abc.com,41629545
lauren.simpson@abc.com,28051902
lukesniewski@abc.com,44768162
mel.chambers@abc.com,39306563
melferdon@abc.com,17021718
isaac-mercedesg@abc.com,20617060
michael.richards@abc.com,20795844
nat.voisey@abc.com,53633788
phillipwsimpson@abc.com,65347141
pirzadr@abc.com,43580309
Rose.Sherlock@abc.com,92037880
steve@abc.com,23050956
Steve.Voisey@abc.com,49560673
suzanne.wesley@abc.com,10476617
warren.sly@abc.com,85718319
</code>

Note that it is using Mac OSX line feeds

The seahub logfile is blank however the django request log is as follows:

<code>
2015-03-10 12:27:06,200 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/middleware/common.py", line 57, in process_request
    host = request.get_host()
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/http/request.py", line 72, in get_host
    "Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): %s" % host)
SuspiciousOperation: Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): *.abc.com
2015-03-11 06:32:55,786 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-12 02:03:09,407 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-12 13:59:09,521 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-13 05:31:57,036 [WARNING] django.request:146 get_response Not Found: /cgi-bin/test-cgi
2015-03-13 05:42:40,129 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-14 03:15:53,395 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-15 23:44:59,425 [WARNING] django.request:146 get_response Not Found: /vtigercrm/
2015-03-17 09:57:28,374 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /useradmin/batchadduser/
Traceback (most recent call last):
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/base/decorators.py", line 20, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/views/sysadmin.py", line 1279, in batch_add_user
    for row in reader:
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
2015-03-17 09:57:28,526 [WARNING] django.request:146 get_response Not Found: /favicon.ico
2015-03-17 09:57:34,192 [WARNING] django.request:146 get_response Not Found: /useradmin/batchadduser/
2015-03-17 10:28:24,288 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /useradmin/batchadduser/
Traceback (most recent call last):
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/base/decorators.py", line 20, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/4es/seafile-server-4.0.6/seahub/seahub/views/sysadmin.py", line 1279, in batch_add_user
    for row in reader:
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
2015-03-17 10:28:24,386 [WARNING] django.request:146 get_response Not Found: /favicon.ico
2015-03-17 10:54:47,193 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/middleware/common.py", line 57, in process_request
    host = request.get_host()
  File "/opt/4es/seafile-server-4.0.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/http/request.py", line 72, in get_host
    "Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): %s" % host)
SuspiciousOperation: Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): *.abc.com
2015-03-17 16:58:50,903 [WARNING] django.request:146 get_response Not Found: /admin/config.php
2015-03-17 20:14:07,005 [WARNING] django.request:146 get_response Not Found: /admin/config.php
</code>

<i>NOTE: I have stripped out the relevant domain names from both files.</i>

**Comment by dakira** [comment]
I was able to do this without problems on a Linux machine and a Mac (both using the same line endings), you problem lies elsewhere.
