### ISSUE TITLE
Download link still valid after file deletion

### ISSUE THREAD

**Issue by warrenseine** [haiwen/seafile#1283]
Hi,

I think this is quite a critical issue we have here. I tested this with Seafile 4.2.2. Not sure if this issue exists in lower versions.

Reproduce steps :
* upload a file via Seahub
* download the file via Seahub
* copy the download link used to download the file
* delete the file via Seahub
* re-access the download link
* watch the deleted file being downloaded again

Confirmed with the Web API too.

I think Seafile should immediately clear all generated download links when a file is deleted.

Regards,
Warren.

**Comment by freeplant** [comment]
The link will be valid for one hour.

**Comment by warrenseine** [comment]
Ok. Is this "by design"? This doesn't sound right.

When I delete a file, where does the data go? Is it going to a "trash bin" where garbage is collected every hour?

**Comment by freeplant** [comment]
I mis-understood you mean.

Since Seafile's keeps history of files until GCed, the file is still there. But the download link is only accessible by login users that have rights to view the file. Why do you think it is a major security problem?

Of course, the program can be improved by checking whether the path still existing.

**Comment by warrenseine** [comment]
I think this is a security problem because from what I understand, this is probably also the case for shared files.

**Comment by shoeper** [comment]
I've just tested this, and it leads to an interesting issue:

I've created a folder test in a library and uploaded a file to it. I shared the file. Logged out and verified that I am able to download it. I logged in again and removed the folder. I've logged out again and tried to download the file again, I got this now:
```
Page unavailable

Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later.
```
And using the direct link I was previously using lead to `Bad access token`. So no security issue here, but a bug, because after logging in again and acessing https://seafile.url/share/links/ I also get same message I got above.

So, how can I view and edit my share links now?

**Comment by shoeper** [comment]
This 
```
Page unavailable

Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later.
``` 
also survives server restarts :o

Here an entry from my django_request.log:
```
2015-06-19 18:51:20,804 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /share/links/
Traceback (most recent call last):
  File "/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/seafile/seafile-pro-server-4.2.0/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-4.2.0/seahub/seahub/base/decorators.py", line 41, in _decorated
    return func(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-4.2.0/seahub/seahub/share/views.py", line 540, in list_shared_links
    if seafile_api.get_file_id_by_path(r.id, fs.path) is None:
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 154, in get_file_id_by_path
    return seafserv_threaded_rpc.get_file_id_by_path(repo_id, path)
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
SearpcError: Path does not exists /test
```

**Comment by shoeper** [comment]
And here the entry logged, when accessing the share link:
```
2015-06-19 18:34:39,984 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /f/0fd5b68cc0/
Traceback (most recent call last):
  File "/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/seafile/seafile-pro-server-4.2.0/seahub/seahub/views/file.py", line 712, in view_shared_file
    obj_id = seafile_api.get_file_id_by_path(repo_id, path)
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 154, in get_file_id_by_path
    return seafserv_threaded_rpc.get_file_id_by_path(repo_id, path)
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/seafile/seafile-pro-server-4.2.0/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
SearpcError: Path does not exists /test
```

IMO when deleting a file or folder seafile should immediately invalide all access tokens to those file (or files and folders if a folder has been removed) and should delete all shares related with deletion action.

**Comment by shoeper** [comment]
now, few hours and some restarts later I can access the page again and no errors are thrown anymore. Could imagine that some background service run in the meantime but don't know. Furthermore the server should never show a hiccup message after the described actions.
