### ISSUE TITLE
4.3.1 DatabaseError: database is locked Page unavailable: after accessing from 3 different clients 

### ISSUE THREAD

**Issue by confile** [haiwen/seafile#1346]
I run Seafile 4.3.1 on RaspberryPi. 

After accessing from three different clients I get the following error in the browser.

![page_unavailable](https://cloud.githubusercontent.com/assets/64265/9293645/20c9ef0e-4433-11e5-9248-e3f5e86085f1.png)

**Comment by confile** [comment]
Here are the last lines in the log files: ``seahub_django_request.log``: 

```
DatabaseError: database is locked
2015-08-16 22:21:24,583 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /api2/repos/9afced4f-79f2-4bb8-9246-dcaa7a8704f8/thumbnail/
Traceback (most recent call last):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 185, in get_response
    response = middleware_method(request, response)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/middleware.py", line 38, in process_response
    request.session.save()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/db.py", line 57, in save
    obj.save(force_insert=must_create, using=using)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 622, in save_base
    manager.using(using).filter(pk=pk_val).exists())):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 610, in exists
    return self.query.has_results(using=self.db)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/query.py", line 447, in has_results
    return bool(compiler.execute_sql(SINGLE))
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
2015-08-16 22:21:26,728 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /api2/ping/
Traceback (most recent call last):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/middleware/locale.py", line 23, in process_request
    request, check_path=check_path)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/utils/translation/__init__.py", line 126, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/utils/translation/trans_real.py", line 390, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/base.py", line 55, in get
    return self._session.get(key, default)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/base.py", line 167, in _get_session
    self._session_cache = self.load()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/db.py", line 18, in load
    expire_date__gt=timezone.now()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 398, in get
    num = len(clone)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 106, in __len__
    self._result_cache = list(self.iterator())
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 317, in iterator
    for row in compiler.results_iter():
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
2015-08-16 22:28:21,829 [WARNING] django.request:144 get_response Not Found: /apple-touch-icon.png
2015-08-16 22:28:29,344 [WARNING] django.request:144 get_response Not Found: /apple-touch-icon.png
2015-08-16 22:29:57,572 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /api2/ping/
Traceback (most recent call last):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/seahub/auth/middleware.py", line 18, in process_request
    request.session.flush()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/base.py", line 262, in flush
    self.delete()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/contrib/sessions/backends/db.py", line 70, in delete
    Session.objects.get(session_key=session_key).delete()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 674, in delete
    collector.delete()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/deletion.py", line 62, in decorated
    func(self, *args, **kwargs)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/deletion.py", line 316, in delete
    query.delete_batch(pk_list, self.using)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/subqueries.py", line 48, in delete_batch
    self.do_query(self.model._meta.db_table, where, using=using)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/subqueries.py", line 33, in do_query
    self.get_compiler(using).execute_sql(None)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
```

``ccnet.log``: 

```
[08/16/15 16:21:17] ../common/session.c(379): Accepted a local client
[08/16/15 16:21:21] ../common/session.c(379): Accepted a local client
[08/16/15 16:21:26] ../common/session.c(379): Accepted a local client
[08/16/15 16:21:29] ../common/peer.c(943): Local peer down
[08/16/15 16:21:30] ../common/peer.c(943): Local peer down
[08/16/15 16:21:35] ../common/peer.c(943): Local peer down
[08/16/15 16:33:00] ../common/peer.c(943): Local peer down
[08/16/15 16:33:00] ../common/peer.c(943): Local peer down
[08/16/15 16:33:00] ../common/peer.c(943): Local peer down
[08/16/15 16:33:01] ../common/peer.c(943): Local peer down
[08/16/15 16:33:01] ../common/peer.c(943): Local peer down
[08/16/15 16:33:16] ../common/session.c(350): Exit at Sun Aug 16 16:33:16 2015
```

``seahub.log``: 

```
DatabaseError: database is locked
2015-08-08 20:12:36,311 [ERROR] seahub.api2.authentication:141 authenticate_v2 error when save token v2:
Traceback (most recent call last):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/seahub/api2/authentication.py", line 139, in authenticate_v2
    token.save()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/seahub/api2/models.py", line 131, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 626, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 605, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 1020, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
2015-08-08 20:12:36,311 [ERROR] seahub.api2.authentication:141 authenticate_v2 error when save token v2:
Traceback (most recent call last):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/seahub/api2/authentication.py", line 139, in authenticate_v2
    token.save()
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/seahub/api2/models.py", line 131, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/base.py", line 622, in save_base
    manager.using(using).filter(pk=pk_val).exists())):
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/query.py", line 610, in exists
    return self.query.has_results(using=self.db)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/query.py", line 447, in has_results
    return bool(compiler.execute_sql(SINGLE))
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/seafile/seafile-server-4.3.1/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database is locked
```

**Comment by confile** [comment]
@shoeper Do you have any idea what is going on here?

**Comment by shoeper** [comment]
Are you using SQLite? Have you checked permissions of your database file?

**Comment by confile** [comment]
yes I am using SQLite as suggested on RaspberryPi following [this](http://draptik.github.io/blog/2014/04/21/installing-seafile-on-raspberry-pi/) tutorial.

**Comment by confile** [comment]
How do I check that permissions?

**Comment by shoeper** [comment]
with ls -l?

**Comment by confile** [comment]
where do I find the file?

**Comment by shoeper** [comment]
I think it's name is seahub.db.

**Comment by confile** [comment]
```
-rw-r--r-- 1 seafile seafile   693248 Aug 16 16:50 seahub.db
```

**Comment by shoeper** [comment]
look fine. Try to restart seahub.

**Comment by confile** [comment]
I did the restart many times. Does not help. What else to do?

**Comment by shoeper** [comment]
> Check for crashed processes
A crashed or zombied process may be keeping a connection to the database, effectively locking it. This can be checked on linux/macosx by running a lsof | grep path_cache command which will display any process which is accessing the path cache file. Also, check if there are any lock files or journal files residing next to the path cache file for the current project. This is also an indication of a crashed or zombied process. Sqlite tries to auto recover as much as possible, but as long as there is a handle open to the database, this may cause the database to lock. - https://support.shotgunsoftware.com/entries/95443658

**Comment by shoeper** [comment]
http://stackoverflow.com/a/3481134

**Comment by confile** [comment]
@shoeper Question. Is there a REST api or something I can use th build my own client which connects to my private server?

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/index.html

**Comment by shoeper** [comment]
Were you able to fix the issue?

**Comment by confile** [comment]
still going through your posts.

**Comment by confile** [comment]
Still working on it. I read somewhere that it might be a timeout issue. Should I increase timeout? If yes where?

**Comment by confile** [comment]
@shoeper  Still working on it. I read somewhere that it might be a timeout issue. Should I increase timeout? If yes where?

**Comment by shoeper** [comment]
Simple seahub access shouldn't cause a timeout. If you are using many devices simultaneously you should  better use mysql.

**Comment by confile** [comment]
mysql on raspberryPi? Does it work well there?

**Comment by confile** [comment]
By the way I still get the "Page unavailable" when trying to access seafile with 3 different browsers.

**Comment by confile** [comment]
It turns out that even with two different browsers I get this problem. The connection is somehow locked for one user only why?

**Comment by shoeper** [comment]
That's SQLite. Any write access requires locking the whole database to prevent corruption.

**Comment by confile** [comment]
Okay then I have to switch to MySQL? Is there any tutorial how replace SQLite with MYSQL on Raspberry. I do I have to start over from the beginning here? http://manual.seafile.com/deploy/using_mysql.html

**Comment by confile** [comment]
Found it: http://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html

**Comment by confile** [comment]
The tutorial suggest: 

> Replace the database section in seafile-data/seafile.conf with following lines:

Problem I do not have the seafile-data folder. Any idea?

**Comment by shoeper** [comment]
Yes you have configured a folder where your data is going. That's the seafile-data folder.

**Comment by confile** [comment]
Where is it in my case? How do I find it?

**Comment by shoeper** [comment]
The path ist specified in ./ccnet/seafile.ini

**Comment by confile** [comment]
okay got it: /media/hdd1/seafiledata

it is strange to put the same data on three different positions.
