### ISSUE TITLE
Create account with API give an Internal Server Error

### ISSUE THREAD

**Issue by zellerda** [haiwen/seafile#1382]
Hello I have this error log when I try to create an account with the API.

2015-09-15 14:06:55,992 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /api2/accounts/myemail@gmail.com/
Traceback (most recent call last):
  File "/cloud/seafile-server-4.3.2/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/cloud/seafile-server-4.3.2/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/cloud/seafile-server-4.3.2/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/cloud/seafile-server-4.3.2/seahub/thirdpart/rest_framework/views.py", line 363, in dispatch
    response = self.handle_exception(exc)
  File "/cloud/seafile-server-4.3.2/seahub/thirdpart/rest_framework/views.py", line 360, in dispatch
    response = handler(request, *args, **kwargs)
  File "/cloud/seafile-server-4.3.2/seahub/seahub/api2/views.py", line 374, in put
    return self._create_account(request, email)
  File "/cloud/seafile-server-4.3.2/seahub/seahub/api2/views.py", line 291, in _create_account
    copy = request.DATA.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
2015-09-15 14:06:55,995 [WARNING] django.request:152 process_view Forbidden (Referer checking failed - no Referer.): /api2/accounts/myemail@gmail.com/

**Comment by shoeper** [comment]
> 2015-09-15 14:06:55,995 [WARNING] django.request:152 process_view Forbidden (Referer checking failed - no Referer.)

**Comment by zellerda** [comment]
The problem is not the warning, its the ERROR

**Comment by shoeper** [comment]
Ok sorry. It could be some problem with encoding, but I don't know more about this.

**Comment by zellerda** [comment]
I have try with the pro version, same problem, below the request I use:
```
PUT /api2/accounts/test@test.com/?password=pass&is_staff=0&is_active=1 HTTP/1.1
Host: cloud.myhost.com
Accept: */*
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Ace_Http_Client
Authorization: Token mytoken
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
```

**Comment by xiez** [comment]
hi, your request arguments should in `-d "password=..."`, for details, plz refer to http://manual.seafile.com/develop/web_api.html#create-account

**Comment by zellerda** [comment]
Ok I found ! its a problem with Zend_Http_Client_Adapter_Curl
