### ISSUE TITLE
 Thumbnails not generated : unsupported format character 'U' (0x55) at index error

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seafile#1457]
Looks like something is not (de)escaped correctly ?
This is the latest Pro server, 4.4.6, as you can see on Fedora Core 21, so Python 2.7. It's 64bit.

2015-11-20 18:34:36,271 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /repo/bb0726d5-4bc3-4e3f-8f53-1ced99631d77/raw/Camera Uploads/repo/bb0726d5-4bc3-4e3f-8f53-1ced99631d77/raw/Camera%20Uploads/1443957357759.jpg
Traceback (most recent call last):
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 151, in get_response
    response = callback(request, **param_dict)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/views/defaults.py", line 26, in page_not_found
    return http.HttpResponseNotFound(template.render(RequestContext(request, {'request_path': request.path})))
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 413, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/urlresolvers.py", line 522, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/seafile/seafile-pro-server-4.4.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/urlresolvers.py", line 415, in _reverse_with_prefix
    candidate = (prefix_norm + result) % dict(zip(prefix_args + params, unicode_args))
ValueError: unsupported format character 'U' (0x55) at index 56

**Comment by tomchiverton** [comment]
Although images via share links work, clicking on them in the files view does not - Apache logs a 500 error, but there is nothing in any of the seafile logs from the same time.

**Comment by freeplant** [comment]
Is the bug still there in version 5.0?

**Comment by shoeper** [comment]
No further information given.

**Comment by tomchiverton** [comment]
woa, steady on, you've asked me to test a major version upgrade - I can't turn that around in a month.

**Comment by tomchiverton** [comment]
Still occurs in Pro version v5.0.6. New stack, generated when click a photo's file name. The overlay opens in the web browser, but noting loads, as before.
```
2016-03-06 09:51:59,434 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /repo/db620eaa-eed3-409c-82d9-910efbda754b/raw/My Photos/100ANDRO/DSC_0012 (1).JPG/repo/db620eaa-eed3-409c-82d9-910efbda754b/raw/My%20Photos/100ANDRO/DSC_0012%20(1).JPG
Traceback (most recent call last):
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 151, in get_response
    response = callback(request, **param_dict)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/views/defaults.py", line 26, in page_not_found
    return http.HttpResponseNotFound(template.render(RequestContext(request, {'request_path': request.path})))
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 413, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/urlresolvers.py", line 522, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/seafile/seafile-pro-server-5.0.6/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/urlresolvers.py", line 415, in _reverse_with_prefix
    candidate = (prefix_norm + result) % dict(zip(prefix_args + params, unicode_args))
ValueError: unsupported format character 'P' (0x50) at index 52

```

**Comment by shoeper** [comment]
Which apache version is being used?

**Comment by shoeper** [comment]
It is very very likely an encoding issue of apache. Have a look at the recently updated manual and make sure you've got an up to to date apache version because several users have reported problems when not having the most recent version (many distributions ship with older versions).

**Comment by tomchiverton** [comment]
I have upgraded to Fedora 23 today, which ships httpd-2.4.18-1.

Still crashes.

**Comment by tomchiverton** [comment]
Why has this been closed ?

**Comment by shoeper** [comment]
Because this is - as written in my last answer a configuration issue. A configuration issue is no bug in the software itself and this is an issue tracker. I've just tested it myself an it works using 5.0.5.
