### ISSUE TITLE
Libraries not loading after upgrading from 4.0.6 to 5.0.3

### ISSUE THREAD

**Issue by Faz100** [haiwen/seafile#1492]
Hi,

I have just upgraded from 4.0.6 to 5.0.3 (following each upgrade script till 4.4 to 5.0) and it seemed to have worked fine except when I log in to Seafile server the libraries are not loading -see attached screenshot.

![seafile error](https://cloud.githubusercontent.com/assets/5108965/12080073/42b8c66c-b247-11e5-8330-e8d945933c12.png)

I also noticed these errors in the seahub_django_request.log:

2016-01-04 00:26:32,812 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /seafile/
Traceback (most recent call last):
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/views/__init__.py", line 1282, in libraries
    }, context_instance=RequestContext(request))
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 172, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 166, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/seafmedia/css/seahub.css?t=1398068110' isn't accessible via COMPRESS_URL ('/media/') and can't be compressed
2016-01-04 00:26:48,322 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /seafile/
Traceback (most recent call last):
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/seahub/views/__init__.py", line 1282, in libraries
    }, context_instance=RequestContext(request))
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/Django-1.5.12-py2.7.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 172, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 166, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/usr/cloud/seafile-server
-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/usr/cloud/seafile-server-5.0.3/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/seafmedia/css/seahub.css?t=1398068110' isn't accessible via COMPRESS_URL ('/media/') and can't be compressed

4.0.6 was working fine before. Any idea on what I need to do?

Faisal

**Comment by shoeper** [comment]
https://forum.seafile-server.org/
