### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by weaming** [haiwen/seafile#1536]
```
---------------------------------
This is your configuration
---------------------------------

    server name:            cloud
    server ip/domain:       example.com

    seafile data dir:       /www/haiwen/seafile-data
    fileserver port:        8082

    database:               create new
    ccnet database:         ccnet-db
    seafile database:       seafile-db
    seahub database:        seahub-db
    database user:          root



---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

Traceback (most recent call last):
  File "setup-seafile-mysql.py", line 1286, in <module>
    main()
  File "setup-seafile-mysql.py", line 1239, in main
    ccnet_config.generate()
  File "setup-seafile-mysql.py", line 755, in generate
    if Utils.run_argv(argv, env=env_mgr.get_binary_env()) != 0:
  File "setup-seafile-mysql.py", line 82, in run_argv
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by freeplant** [comment]
Please ask installation problem in our forum.

**Comment by towa48** [comment]
This is a very old issue but i have not found any answers to this.

Your processor architecture incompatible with downloaded distro. You should probable compile it by yourself. To understand the problem try execute
```
./seafile/bin/ccnet-init
file ./seafile/bin/ccnet-init
```
