### ISSUE TITLE
IntegrityError: Unique-Constraint „base_userlastlogin_pkey“

### ISSUE THREAD

**Issue by mhaze4** [haiwen/seafile#1576]
Hello,

I wanted to change the email address of my existing user. Since this is not possible I created a new one with the new desired email address. After logging in with the new user I get this error for some reason:

> Page unavailable
   Sorry, but the requested page is unavailable due to a server hiccup.
   Our engineers have been notified, so check back later.

A quick research showed me to take a look into seahub_django_request.log file where the following exception is thrown:

> 2016-03-28 03:53:59,771 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/views/__init__.py", line 1186, in libraries
    create_default_library(request)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/views/__init__.py", line 1106, in create_default_library
    UserOptions.objects.disable_user_guide(username)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/options/models.py", line 104, in disable_user_guide
    VAL_USER_GUIDE_OFF)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/seahub/options/models.py", line 42, in set_user_option
    user_option.save(using=self._db)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/srv/www/seafile/seafile-server-5.0.5/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
IntegrityError: FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint „options_useroptions_pkey“
DETAIL:  Schlüssel „(id)=(1)“ existiert bereits.

Login with the existing user is still possible.
How can I fix this or what could be the reason for?

Any help would be really appreciated :sos:

**Comment by killing** [comment]
The forum (https://forum.seafile-server.org/) is more appropriate for this issue. You can get more help from the community there. Here is for bug tracking only.
I'm closing this issue.
