### ISSUE TITLE
Seahub "Page unavailable" after upgrade 4.0.1 to 5.1.1

### ISSUE THREAD

**Issue by hipkinsgnom** [haiwen/seafile#1600]
After upgrade 4.0.1 to 5.1.1, when go to root webUI - see:

> Page unavailable
> Sorry, but the requested page is unavailable due to a server hiccup.
> Our engineers have been notified, so check back later.

**seafile.conf**
```
[network]
port = 12001

[fileserver]
port = 8082

[database]
*
```

**seahub_settings.py**
```
SECRET_KEY = "*"
FILE_SERVER_ROOT = 'https://mydomain/seafhttp'
SERVE_STATIC = False
MEDIA_URL = '/seafmedia/'
SITE_ROOT = '/seafile/'

DATABASES
*
```

**seahub.init.log**
```
LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub (fastcgi) at 127.0.0.1:8000 ...

Seahub is started

Done.
```

**seahub_django_request.log**
```
2016-04-22 16:05:14,042 [WARNING] django.request:170 get_response Not Found: /seafile/seafmedia
2016-04-22 16:05:18,098 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /seafile/
Traceback (most recent call last):
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/seahub/views/__init__.py", line 884, in libraries
    }, context_instance=RequestContext(request))
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 172, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 166, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/home/max/seafile/seafile-server-5.1.1/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/seafmedia/css/seahub.css?t=1398068110' isn't accessible via COMPRESS_URL ('/media/') and can't be compressed
```

**Comment by xiez** [comment]
hi,

try remove seahub cache by `rm -rf /tmp/seahub_cache/*` or restart memcached.

**Comment by hipkinsgnom** [comment]
Hello, i checked seahub_cache/ after done upgrade scripts, it was empty.
Ok, so i did `sudo rm -rf /tmp/seahub_cache/*` now. Doesnt help...((

**Comment by xiez** [comment]
Any cache related config in seahub_settings.py ?

**Comment by hipkinsgnom** [comment]
Nope, entire seahub_settings.py stored in head of this page, except database block.

**Comment by xiez** [comment]
u need to modify a few seahub settings according to http://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html

**Comment by hipkinsgnom** [comment]
I changed seahub_settings.py to 
```
FILE_SERVER_ROOT = 'https://mydomain/seafhttp'
SERVE_STATIC = False
MEDIA_URL = '/seafmedia/'
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + 'assets/'
SITE_ROOT = '/seafile/'
LOGIN_URL = '/seafile/accounts/login/'
```

And it works! Thx xiez.
