### ISSUE TITLE
[bug] seafile-server 5.1.2 FreeBSD port goes wrong when uploading hundreds of files in one folder

### ISSUE THREAD

**Issue by tianyang-abc** [haiwen/seafile#1644]
The seafile-server 5.1.2 source codes were ported to FreeBSD 10.3-x64 in help with patches from ports/net-mngt/seafile. In company with ported ccnet and seahub, the whole service seems OK. 

But when uploading 300 or 400 files into one folder of a Library in seafile, the service was broken in FreeBSD. And it's also impossible to view the list of the Library with hundreds of files in one folder.

seafile.log
> [05/15/2016` 17:02:41] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:02:41] size-sched.c(268): [scheduler] Failed to compute size of repo 6ebc1dfb.
> [05/15/2016 17:02:42] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:02:42] size-sched.c(268): [scheduler] Failed to compute size of repo 6ebc1dfb.
> [05/15/2016 17:09:35] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:18:58] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:19:11] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:19:12] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 17:19:14] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.
> [05/15/2016 19:19:20] ../common/fs-mgr.c(1704): Failed to load seafdir json object: maximum parsing depth reached near '33188'.

seahub_django_request.log
> 2016-05-15 19:19:20,507 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /ajax/lib/6ebc1dfb-cf43-43af-9821-a5797942c5b5/dir/
> Traceback (most recent call last):
> File "/haiwen/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/haiwen/seafile-server-5.1.2/seahub/seahub/auth/decorators.py", line 69, in wrappedview
return view_func(request, *args, **kwargs)
> File "/haiwen/seafile-server-5.1.2/seahub/seahub/views/ajax.py", line 296, in list_lib_dir
username, -1, -1)
> File "/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
> return fret(ret_str)
> File "/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 79, in fretobjlist
> raise SearpcError(dicts['err_msg'])
> SearpcError: Bad dir id

seahub.log
> 2016-05-15 15:17:18,032 [ERROR] seahub.api2.views:1457 get_dir_entrys_by_id Bad dir id
> 2016-05-15 15:17:26,542 [ERROR] seahub.api2.views:1457 get_dir_entrys_by_id Bad dir id
> 2016-05-15 15:25:05,516 [ERROR] seahub.api2.views:1457 get_dir_entrys_by_id Bad dir id

According to the log, it's possible that **libjansson.so** in FreeBSD is different from that in Linux? 
Any hints is greatly appreciated.

Tian Yang
May 16, 2016

**Comment by tianyang-abc** [comment]
Jansson (libjansson.so)
> The limit is configurable via the JSON_PARSER_MAX_DEPTH setting
> within jansson_config.h and is set by default to 2048.
