### ISSUE TITLE
Django-1.8.10 crash

### ISSUE THREAD

**Issue by leeyuentuen** [haiwen/seafile#1655]
log from  seahub_django_request.log
already try clear folder in /tmp/seahub_cache
using Seafile 5.1.2

```
2016-05-24 04:23:50,333 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/middleware/locale.py", line 32, in process_request
    request, check_path=check_path)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/translation/__init__.py", line 198, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/translation/trans_real.py", line 503, in get_language_from_request
    lang_code = request.session.get(LANGUAGE_SESSION_KEY)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/contrib/sessions/backends/base.py", line 59, in get
    return self._session.get(key, default)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/sql/compiler.py", line 838, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/seafile/seafile-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

```

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
