### ISSUE TITLE
Seafile Server 6.0.3 can not delete linked device

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1757]
We are having issues with users not able to delete a linked device from seafile.  An admin can delete the device.  In seafile 5.1 a normal user could delete a device.

**Comment by caniwi** [comment]
This only appears to be an issue for mobile devices.  Deleting desktop clients is fine for a normal user.  Definitely Android but we have not yet confirmed that it affects Apple.

**Comment by szponek** [comment]
Same thing happens on my instance, Firefox console shows error 500 on DELETE /api2/devices/

I tried running curl to get the same behaviour:

`curl -X DELETE -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "Authorization: Token $TOKEN" https://$SERVER/api2/devices/ -d 'platform=android&device_id=<redacted>&wipe_device=true'`

I get: {"success":true} in return instead of a 500, but the device doesn't get deleted.

**Comment by szponek** [comment]
seahub_django_request.log has this error after I try to delete my device:

`2016-09-16 13:23:12,681 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/devices/
Traceback (most recent call last):
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/api2/views.py", line 1866, in delete
    remote_wipe=remote_wipe)
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/utils/devices.py", line 31, in do_unlink_device
    TokenV2.objects.mark_device_to_be_remote_wiped(username, platform, device_id)
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/api2/models.py", line 119, in mark_device_to_be_remote_wiped
    token.save()
  File "/home/seafile/seafile-server-6.0.3/seahub/seahub/api2/models.py", line 161, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/seafile/seafile-server-6.0.3/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: invalid input syntax for type inet: "<redactedipaddress>                         "
LINE 1: ...16T13:23:12.677782'::timestamp, "last_login_ip" = E'<redactedipaddress>`

**Comment by freeplant** [comment]
It seems that the last_login_ip field is invalid. What is the value in your case?

**Comment by szponek** [comment]
The IP was OK, but it looks like it got right padded with spaces. See 'curl .../api2/devices/' output:

`{
        "client_version": "1.7.0",
        "device_id": "<redacted_device_id>",
        "device_name": "SM-T230",
        "is_desktop_client": false,
        "key": "<redacted_key>",
        "last_accessed": "2016-09-17T13:04:21+08:00",
        "last_login_ip": "<redacted_ip>/32                       ",
        "platform": "android",
        "platform_version": "4.4.2",
        "user": "<redacted_username>",
        "wiped_at": null
    },`

It seems this padding is a normal behaviour of PostgreSQL for char fields and this thread in django-users https://groups.google.com/d/msg/django-users/SrkBAAJ4qQg/3B4PR5BPYUIJ confirms padding can appear in django output sometimes. Not sure why it doesn't cause issues on Seafile 5.1.x. My prod instance is still in 5.x, spaces appear in /api2/devices/' output, but I can unlink my devices successfully, while it fails on my v6.x test instance.

I changed last_login_ip field from char(39) to varchar (39) in PostgreSQL on my test instance, with:

`ALTER TABLE api2_tokenv2 ALTER COLUMN last_login_ip TYPE varchar(39) USING rtrim(last_login_ip);`

 and I can delete my devices without issues now.

**Comment by szponek** [comment]
Looks like github trims spaces in <code> blocks, and leaves just one, there were 23 spaces in 'last_login_ip' after '<redacted_ip>/32'

**Comment by szponek** [comment]
As the issue author pointed out, desktop client devices weren't affected, although they also had padding spaces in last_login_ip field (at least in my case), yet I was able to unlink them just fine. This makes me believe there is a trim() function missing somewhere in seahub.

**Comment by freeplant** [comment]
The problem is fixed in version 6.0.4.
