### ISSUE TITLE
mysql5.7 and default_storage_engine

### ISSUE THREAD

**Issue by benni336** [haiwen/seafile#1776]
Hey all,

after moving from Ubuntu 14.04 to 16.04
I noticed that I had problems starting up seahub in fastcgi mode.

It took me a while but it should be definitely noticed somewhere in the manual, that with **upgrading MySQL to version 5.7** it is nescarry to **adopt `seahub_settings.py`** and "flush" them by deleting `seahub_settings.pyc`

### Error Message
After restoring all files in the database I got the following error when starting up `seahub.sh start-fastcgi 8000`:
```
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/home/seafile/seafile-server-6.0.4/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 444, in execute
    self.check()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 1205, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 1282, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 934, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/validation.py", line 18, in check_field
    field_type = field.db_type(connection)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1193, "Unknown system variable 'storage_engine'")

Error:Seahub failed to start.
```

The error could only be noticed with `./seahub.sh start-fastcgi` not with just `./seahub.sh start`

### Solution
Referring to [this post on StackExchange]( http://stackoverflow.com/questions/37175295/cant-migrate-django-databases-on-mysql-after-upgrading-to-ubuntu-16-04) and [this one](http://dba.stackexchange.com/questions/101908/migrate-jira-to-mysql-unknown-system-variable-storage-engine) `~/conf/seahub_settings.py` should be updated by adapting l.23 from
`'init_command': 'SET storage_engine=INNODB',` to
`'init_command': 'SET default_storage_engine=INNODB',`

See more detailed example below:

**old/wrong file seahub_settings.py**
```Python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seahub-db',
        'USER': 'seafile',
        'PASSWORD': '**********',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET storage_engine=INNODB',
        }
    }
}
```

**new/right file seahub_settings.py**
```Python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seahub-db',
        'USER': 'seafile',
        'PASSWORD': 'JGrD3v6SUP',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=INNODB',
        }
    }
}
```

Using adapted Version under older MySQL-Versions could not be checked.

**Comment by killing** [comment]
Actually with MySQL 5.7, you don't need to add the "SET" command. In the current version of Seafile, the setup-seafile-mysql script will not add this command. The problem only happens for upgrading from older version of Seafile. We'll add this to FAQ.

**Comment by benni336** [comment]
So the `'Options':{...}` Part can safely be removed?

**Comment by killing** [comment]
Yes.
