### ISSUE TITLE
Webdav Upload Fail Umlauts (äöü)

### ISSUE THREAD

**Issue by WeWin55** [haiwen/seafile#1789]
Hello,

ive got a problem while uploading pdfs with umlauts in the name. [example: 20161028 - illö.pdf] 
The webdav client just gives the error "upload failed" in seafile the file has 0 byte and is named "20161028 - illö.pdf".
I think it has something to do with the locales..

The seafdav.log prints out this error:

`[2016-10-28 16:12:14,536](e.srcexception:):  Traceback (most recent call last):
  File "/opt/seafile/seafile-server-6.0.5/seahub/thirdpart/wsgidav/error_printer.py", line 43, in **call**
    for v in app_iter:
  File "/opt/seafile/seafile-server-6.0.5/seahub/thirdpart/wsgidav/request_resolver.py", line 201, in **call**
    for v in app_iter:
  File "/opt/seafile/seafile-server-6.0.5/seahub/thirdpart/wsgidav/request_server.py", line 113, in **call**
    app_iter = method(environ, start_response)
  File "/opt/seafile/seafile-server-6.0.5/seahub/thirdpart/wsgidav/request_server.py", line 638, in doPUT
    res = parentRes.createEmptyResource(util.getUriName(path))
  File "/opt/seafile/seafile-server-6.0.5/seahub/thirdpart/wsgidav/addons/seafile/seafile_dav_provider.py", line 335, in createEmptyResource
    raise DAVError(HTTP_INTERNAL_ERROR)
DAVError: DAVError(500 Internal Server Error: An internal server error occurred)

None
`

And my seafdav.conf looks like this.

[WEBDAV]
enabled = true
port = 8080
fastcgi = true
share_name = /seafdav

**Comment by caixiangyue** [comment]
We will fix this bug in 7.1.
