### ISSUE TITLE
6.0.4: AttributeError: 'tuple' object has no attribute 'pop'

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1815]
```
2016-12-17 13:07:52,690 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/starredfiles/
Traceback (most recent call last):
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-6.0.4/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/seafile/seafile-pro-server-6.0.4/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/seafile/seafile-pro-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/seafile/seafile-pro-server-6.0.4/seahub/seahub/api2/throttling.py", line 129, in allow_request
    self.history.pop()
AttributeError: 'tuple' object has no attribute 'pop'
```

**Comment by shoeper** [comment]
Look like this was due to cached items from a prior version.
