### ISSUE TITLE
Cant use the Android/iOS/Windows Sync client

### ISSUE THREAD

**Issue by Kopertje** [haiwen/seafile#1823]
Hello,

After updating from 5.1.11 to 6.0.5 i cant seem to use the sync client anymore.
I also had the problem of not showing tumbnails when there is a space in the folder name. I Fixed this y using the following commands :

apt-get install apache2 subversion libapache2-mod-svn
a2enmod dav_svn
svnadmin create /srv/svn
chown -R www-data: /srv/svn
cat > /etc/apache2/mods-available/dav_svn.conf << EOF
<Location /svn>
  DAV svn
  SVNPath /srv/svn
</Location>
EOF
service apache2 restart

Source: https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641

When i take a look in my seahub_django_request.log i get this following errors from trying to get the liberies information on the sync client for Windows. The Android app gives an error messages "Internal server error"

**seahub_django_request.log:**

OperationalError: (1054, "Unknown column 'api2_tokenv2.created_at' in 'field list'")
2017-01-04 09:54:18,306 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/repos/
Traceback (most recent call last):
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/my/install/folder/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/my/install/folder/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 376, in initial
    self.perform_authentication(request)
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 310, in perform_authentication
    request.user
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/request.py", line 353, in __getattribute__
    return super(Request, self).__getattribute__(attr)
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/request.py", line 193, in user
    self._authenticate()
  File "/my/install/folder/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/request.py", line 316, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/my/install/folder/seahub/seahub/api2/authentication.py", line 63, in authenticate
    ret = self.authenticate_v2(request, key)
  File "/my/install/folder/seahub/seahub/api2/authentication.py", line 92, in authenticate_v2
    token = TokenV2.objects.get(key=key)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/my/install/folder/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'api2_tokenv2.created_at' in 'field list'")

Is there someone who can help me with this issue?

Greetings,
Robin

**Comment by Kopertje** [comment]
Hello,

After running the upgrade script from 5.1 to 6.0 it works again.
This can be closed.

Greetings,
Robin
