### ISSUE TITLE
3 seahub_django_request.log reported errors

### ISSUE THREAD

**Issue by TI-Admin** [haiwen/seafile#1857]
seafile server 6.0.8 on ubuntu 16.04

1st error

```
2017-02-28 13:19:02,265 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/events/
Traceback (most recent call last):
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/throttling.py", line 129, in allow_request
    self.history.pop()
AttributeError: 'tuple' object has no attribute 'pop'

```

2nd error 

```
2017-02-28 13:19:02,265 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/avatars/user/gd@informatik.uni-kiel.de/resized/42/
Traceback (most recent call last):
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/views.py", line 3803, in get
    url, is_default, date_uploaded = api_avatar_url(user, int(size))
ValueError: too many values to unpack

```
3rd error

```
2017-03-06 09:07:28,064 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/repos/
Traceback (most recent call last):
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/api2/views.py", line 466, in get
    "owner_nickname": email2nickname(r.user),
  File "/srv/seafile/informatik/seafile-server-6.0.8/seahub/seahub/base/templatetags/seahub_tags.py", line 370, in email2nickname
    if cached_nickname and cached_nickname.strip():
AttributeError: 'list' object has no attribute 'strip'


```

**Comment by shoeper** [comment]
Have you restarted memcached after upgrading Seafile?

**Comment by TI-Admin** [comment]
No I haven't and I did not notice an instruction to do so. Btw my memcache setup looks like this. Is this deprecated ?

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

```

**Comment by TI-Admin** [comment]
There are conflicting instructions about the memcached configuration in two files

https://manual.seafile.com/config/seahub_settings_py.html
https://manual.seafile.com/deploy/add_memcached.html

Which is true ?

**Comment by killing** [comment]
You should follow the instructions on https://manual.seafile.com/deploy/add_memcached.html . We forgot to update the other link.

This seems to be seahub issue. You can open the issue on seahub project.

**Comment by shoeper** [comment]
When has it been changed? Furthermore there was no hint that existing configurations need an update.

**Comment by freeplant** [comment]
After upgrading to Django 1.8.x in version 6.0, the old memcache config doesn't handle multi-thread correctly. Sometimes (rarely) there will be such error `ValueError: too many values to unpack`.  Using PyLibMCCache will solve the problem.

**Comment by shoeper** [comment]
Thanks for the info. The problem is: I cannot remember you informed anyone of this (I very likely would). Thus all customers are still very likely using the old configuration and can run into this problem. Furthermore even those setting up a new Seafile server including memcached are (possibly) using the old instructions because only parts of the documentation have been updated.
