### ISSUE TITLE
Error occur after login. Can't view files

### ISSUE THREAD

**Issue by wdjwxh** [haiwen/seafile#1933]
can't view my files.
like
![image](https://user-images.githubusercontent.com/3990956/28267262-e449a02a-6b2b-11e7-9912-373d219d3703.png)

```
2017-07-17 20:08:02,427 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/ping/
Traceback (most recent call last):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/throttling.py", line 233, in allow_request
    return super(ScopedRateThrottle, self).allow_request(request, view)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/cache/backends/filebased.py", line 41, in get
    if not self._is_expired(f):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/cache/backends/filebased.py", line 138, in _is_expired
    exp = pickle.load(f)
EOFError
2017-07-17 20:08:03,463 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/account/info/
Traceback (most recent call last):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/seahub/api2/throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/cache/backends/filebased.py", line 41, in get
    if not self._is_expired(f):
  File "/usr/local/wrdcloud/seafile-server-6.0.7/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/cache/backends/filebased.py", line 138, in _is_expired
    exp = pickle.load(f)
EOFError
```

**Comment by marcusm1009** [comment]
Please use the Seafile Forum https://forum.seafile.com
