### ISSUE TITLE
Previewing office docs creates OperationalError: (1054, "Unknown column 'share_fileshare.permission' in 'field list'")

### ISSUE THREAD

**Issue by timtoo** [haiwen/seafile#1963]
This happens when trying to view a office (spreadsheet/document) file. Web page reports "Page unavailable", and the following traceback is in the system logs. Previewing office documents used to work on this server, but hasn't been used in a while. Not sure what upgrade or configuration monkeying may have broken it. Either way, uncaught exceptions, and generic error web pages, aren't usually desirable.

```
 2017-09-24 04:07:01,417 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /lib/d4184681-cdd1-4000-9af8-5d41659f914d/file/cloud/bp.xlsx
 Traceback (most recent call last):
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
     return view_func(request, *args, **kwargs)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/seahub/base/decorators.py", line 74, in _decorated
     return func(request, *args, **kwargs)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/seahub/views/file.py", line 385, in view_lib_file
     return _file_view(request, repo_id, path)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/seahub/views/file.py", line 581, in _file_view
     fileshare = l[0] if len(l) > 0 else None
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 144, in __len__
     self._fetch_all()
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 965, in _fetch_all
     self._result_cache = list(self.iterator())
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 238, in iterator
     results = compiler.execute_sql()
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
     cursor.execute(sql, params)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/utils.py", line 98, in __exit__
     six.reraise(dj_exc_type, dj_exc_value, traceback)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
   File "/home/seafile/seafile-pro-server-6.1.7/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
     return self.cursor.execute(query, args)
   File "/usr/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
     self.errorhandler(self, exc, value)
   File "/usr/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
     raise errorclass, errorvalue
 OperationalError: (1054, "Unknown column 'share_fileshare.permission' in 'field list'")
```

**Comment by timtoo** [comment]
It turned out that upgrades/upgrade_6.0_6.1.sh had never been fully run, and my database schema was out of date.
