### ISSUE TITLE
[ArchLinux] setup-seafile-mysql.sh [raise child_exception]

### ISSUE THREAD

**Issue by jojotango** [haiwen/seafile#1964]
Hello, 
I use [v6.2.1-seafile-server](https://aur.archlinux.org/packages/seafile-server/) and [v6.1.1-seafile](https://aur.archlinux.org/packages/seafile/) x86_64 compiled from source with AUR PKGBUILD.
When I try to [Deploying Seafile with MySQL](https://manual.seafile.com/deploy/using_mysql.html) with setup-seafile-mysql.sh, a child_exception is raising

```
$ ./seafile-server/scripts/setup-seafile-mysql.sh
    ...
    server name:            seafile
    server ip/domain:       192.168.1.28

    seafile data dir:       /home/seafile/exemple.dom/seafile-server/seafile-data
    fileserver port:        8082

    database:               use existing
    ccnet database:         ccnet
    seafile database:       seafile
    seahub database:        seahub
    database user:          seafile

---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

Traceback (most recent call last):
  File "setup-seafile-mysql.py", line 1471, in <module>
    main()
  File "setup-seafile-mysql.py", line 1424, in main
    ccnet_config.generate()
  File "setup-seafile-mysql.py", line 815, in generate
    if Utils.run_argv(argv, env=env_mgr.get_binary_env()) != 0:
  File "setup-seafile-mysql.py", line 85, in run_argv
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
```
Thanks

**Comment by jojotango** [comment]
Sorry I'm not in the right section, you can close this issue. It's because of the package's architecture. I have proposed a [correction](https://github.com/haiwen/seafile-server/pull/75/commits/f2b37055154f6a2547d381504d8adbcab1eaeee9l).
