### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by c0d1ng** [haiwen/seafile#1978]
When I try to log in, I am getting this error (from `seahub_django_request.log`):
```bash
2017-10-26 19:23:40,105 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-6.2.2/seahub/seahub/auth/views.py", line 176, in login
    if form.is_valid():
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 393, in full_clean
    self._clean_form()
  File "/opt/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 417, in _clean_form
    cleaned_data = self.clean()
  File "/opt/seafile/seafile-server-6.2.2/seahub/seahub/auth/forms.py", line 66, in clean
    username = self.get_primary_id_by_username(username)
  File "/opt/seafile/seafile-server-6.2.2/seahub/seahub/auth/forms.py", line 53, in get_primary_id_by_username
    p_id = ccnet_api.get_primary_id(username)
  File "/opt/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 1003, in get_primary_id
    return ccnet_threaded_rpc.get_primary_id(email)
AttributeError: 'CcnetThreadedRpcClient' object has no attribute 'get_primary_id'
2017-10-26 19:23:40,486 [WARNING] django.request:170 get_response Not Found: /favicon.ico
```

This issue ocurred some time ago, however the sync client is still working and I am still logged in with my main browser.

**Comment by kartikagarwal799** [comment]
After upgrading seafile im also facing same issue.


```
> 2018-02-26 12:01:34,769 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /accounts/login/
> Traceback (most recent call last):
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/seahub/auth/views.py", line 113, in login
>     if form.is_valid():
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 184, in is_valid
>     return self.is_bound and not self.errors
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 176, in errors
>     self.full_clean()
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 393, in full_clean
>     self._clean_form()
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/forms/forms.py", line 417, in _clean_form
>     cleaned_data = self.clean()
>   File "/opt/seafile/seafile-server-6.2.5/seahub/seahub/auth/forms.py", line 66, in clean
>     username = self.get_username_by_login(login)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/seahub/auth/forms.py", line 46, in get_username_by_login
>     username = Profile.objects.get_username_by_login_id(login)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/seahub/profile/models.py", line 93, in get_username_by_login_id
>     return super(ProfileManager, self).get(login_id=login_id).user
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 328, in get
>     num = len(clone)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 144, in __len__
>     self._fetch_all()
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 965, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 238, in iterator
>     results = compiler.execute_sql()
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
>     cursor.execute(sql, params)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/opt/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
>     self.errorhandler(self, exc, value)
>   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorvalue
> OperationalError: (1054, "Unknown column 'profile_profile.list_in_address_book' in 'field list'")
> 
> 
```
