### ISSUE TITLE
Data too long for column 'device_name' at row 1

### ISSUE THREAD

**Issue by masseelch** [haiwen/seafile#1979]
I am was trying to sync a local folder on the same machine my seafile-server is running on with the seafile-cli client. I used the following command:

`seaf-cli sync -l "xxxxx" -s "http://127.0.0.1:8000" -d xxx -u "xxxx"`

The client itself generates the error:
```
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 845, in <module>
    main()
  File "/usr/bin/seaf-cli", line 841, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 542, in seaf_sync
    token = get_token(url, username, password, conf_dir)
  File "/usr/bin/seaf-cli", line 235, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data)
  File "/usr/bin/seaf-cli", line 208, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

The `seahub_django_request.log`-file says:
```
2017-10-27 16:28:49,812 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/auth-token/
Traceback (most recent call last):
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/views.py", line 190, in post
    if serializer.is_valid():
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/serializers.py", line 410, in run_validation
    value = self.validate(value)
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/serializers.py", line 100, in validate
    client_version, platform_version)
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/utils.py", line 501, in get_token_v2
    client_version, platform_version, get_client_ip(request))
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/models.py", line 107, in get_or_create_token
    token.save()
  File "[...]/seafile/seafile-server-6.0.4/seahub/seahub/api2/models.py", line 161, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "[...]/seafile/seafile-server-6.0.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DataError: (1406, "Data too long for column 'device_name' at row 1")
```

**Comment by juleeeeeeeeeeees** [comment]
Hi! I'm going through the same problem as yours and would like to get in touch with you or find out how and if you have solved your problem. I await an answer.

**Comment by shoeper** [comment]
Search for the column device_name in your database (on the server) and extend its max length.

**Comment by juleeeeeeeeeeees** [comment]
Okay, but how do I do this? (I'm layman)

**Comment by shoeper** [comment]
@killing @freeplant application should check it. Best solution would probably be to just cut off overlong device names.
