### ISSUE TITLE
memcached bug after upgrade

### ISSUE THREAD

**Issue by TI-Admin** [haiwen/seafile#1992]
After the minor update from seafile 6.2.2 to 6.2.3 I get an error with memcached. Running the server on ubuntu 14.04.5 LTS

```
2017-11-28 16:16:00,350 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:throttle_ping_134.245.252.118): Operation now in progress
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/srv/seafile/informatik/seafile-server-6.2.3/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:throttle_ping_134.245.252.118): Operation now in progress
2017-11-28 16:16:00,350 [ERROR] django.pylibmc:146 set MemcachedError: error 47 from memcached_set: (26429536) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY, host: 127.0.0.1:11211 -> libmemcached/connect.cc:612
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
ServerDown: error 47 from memcached_set: (26429536) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY, host: 127.0.0.1:11211 -> libmemcached/connect.cc:612

```

**Comment by shoeper** [comment]
Have you tried restarting memcached?
