### ISSUE TITLE
 from seaserv import FILE_SERVER_ROOT, FILE_SERVER_PORT, SERVICE_URL ImportError: No module named seaserv

### ISSUE THREAD

**Issue by lovemehaha** [haiwen/seafile#1995]
I tried to compile the scource code, after compilation，I tried to deploy seafile server with guide(https://manual.seafile.com/build_seafile/server.html), I run seafile-admin, an error occurred:

Now initializing seahub database, please wait...

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/haiwen/seafile-server/seahub/seahub/__init__.py", line 3, in <module>
    from handlers import repo_created_cb, repo_deleted_cb
  File "/data/haiwen/seafile-server/seahub/seahub/handlers.py", line 4, in <module>
    import settings
  File "/data/haiwen/seafile-server/seahub/seahub/settings.py", line 9, in <module>
    from seaserv import FILE_SERVER_ROOT, FILE_SERVER_PORT, SERVICE_URL
ImportError: No module named seaserv
Error: Seahub syncdb failed

Is there sth I am missing?

**Comment by killing** [comment]
Please post questions on the forum.
