### ISSUE TITLE
seaf-cli refuses to sync with an existing "Repo" (directory?)

### ISSUE THREAD

**Issue by wsw70** [haiwen/seafile#2065]
seaf-cli (6.1.5) refuses to synchronize after an initial synchronization.

The first synchronization was successful - the contents of the library were downloaded. They were synchronized with

`seaf-cli sync -s https://filesync.example.com/ -u user@example.com -p 1234 -l <the lib UUID> -d ~/seafile/seafile/dev-go
`

Subsequent calls of the same command line crash with

```
Starting to download ...
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 845, in <module>
    main()
  File "/usr/bin/seaf-cli", line 841, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 578, in seaf_sync
    email, random_key, enc_version, more_info)
  File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
pysearpc.common.SearpcError: Repo already exists
```

I am not sure what `Repo` is in the error message above

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by wsw70** [comment]
@shoeper sorry but how can a traceback not be a bug?
