### ISSUE TITLE
Index.log  SwiftAuthenticateError: [swift] Unexpected code when authenticate: 204 (But works for Seahub!)

### ISSUE THREAD

**Issue by MrMoronIV** [haiwen/seafile#2075]
Seafile is working perfectly fine with storing files, reading them, etc. 
The index.log gives this error:

```
    07/22/2018 17:19:28 [ERROR] seafes:119 thread_task: Index Repo Error: 302a0c67-81b0-49e7-b903-20c7a120cbef
    Traceback (most recent call last):
      File "/seafile/seafile-server-latest/pro/python/seafes/index_local.py", line 105, in thread_task
        self.fileindexupdater.update_repo(repo_id, commit_id)
      File "/seafile/seafile-server-latest/pro/python/seafes/file_index_updater.py", line 67, in update_repo
        self.check_recovery(repo_id)
      File "/seafile/seafile-server-latest/pro/python/seafes/file_index_updater.py", line 63, in check_recovery
        self.update_files_index(repo_id, old, new)
      File "/seafile/seafile-server-latest/pro/python/seafes/file_index_updater.py", line 33, in update_files_index
        new_commit = commit_mgr.load_commit(repo_id, 0, new_commit_id)
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/commits.py", line 31, in load_commit
        data = self.obj_store.read_obj(repo_id, version, obj_id)
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/backends/base.py", line 12, in read_obj
        data = self.read_obj_raw(repo_id, version, obj_id)
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/backends/swift.py", line 150, in read_obj_raw
        data = self.swift_client.read_object_content(real_obj_id)
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/backends/swift.py", line 111, in read_object_content
        self.authenticate()
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/backends/swift.py", line 65, in authenticate
        self.authenticate_v1()
      File "/seafile/seafile-server-latest/seahub/thirdpart/seafobj/backends/swift.py", line 59, in authenticate_v1
        ret_code)
    SwiftAuthenticateError: [swift] Unexpected code when authenticate: 204
```

The exact same login credentials are used by the seahub nodes (it's a clustered setup) and they work perfectly fine! Why is the index complaining?

**Comment by shoeper** [comment]
Have read an issue about v1 vs v2 before. Could this be the issue, here? Looks like v1 is being used.

**Comment by MrMoronIV** [comment]
I indeed fixed this by using v2, very weird!
