### ISSUE TITLE
Reverse for 'two-factor-auth-view' not found for /useradmin/info/username/

### ISSUE THREAD

**Issue by Freeaqingme** [haiwen/seafile#2117]
Hi, I configured Seafile to connect it to Ldap. I'm able to log in using the credentials from ldap, but the admin user isn't able to open it at /useradmin/info/username/ . In the logs the following exception is logged:

```2018-10-10 21:55:47,754 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /useradmin/info/freeaqingme/
Traceback (most recent call last):
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile-pro-server-6.3.6/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile-pro-server-6.3.6/seahub/seahub/base/decorators.py", line 26, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/seafile-pro-server-6.3.6/seahub/seahub/views/sysadmin.py", line 763, in user_info
    'reference_id': reference_id if reference_id else '',
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 207, in render
    return self._render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/opt/seafile-pro-server-6.3.6/seahub/thirdpart/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'two-factor-auth-view' with arguments '(u'freeaqingme',)' not found. 1 pattern(s) tried: ['api2/two-factor-auth/(?P<email>\\S+@[a-zA-Z0-9._-]+\\.[a-zA-Z0-9._-]+)/$']

```

Seahub is configured to use mysql, and uses these ldap settings:
```
[LDAP]
HOST = ldaps://ldap.example.net:636/
BASE = ou=users,dc=example,dc=org
USER_DN = cn=seafile1.example.org,ou=seafile,ou=services,dc=example,dc=org
PASSWORD = hunter2
LOGIN_ATTR = uid
# LOGIN_ATTR = mail

[LDAP_SYNC]
ENABLE_GROUP_SYNC = true
SYNC_INTERVAL = 60
GROUP_OBJECT_CLASS = groupOfNames
```

**Comment by freeplant** [comment]
Related issue: https://github.com/haiwen/seafile/issues/2121

**Comment by xiez** [comment]
Hi @Freeaqingme , 

According to https://manual.seafile.com/deploy_pro/using_ldap_pro.html, 

> LOGIN_ATTR: The attribute used for user's unique identifier. Use mail or userPrincipalName.

`LOGIN_ATTR = uid` is not supported right now. Please use `mail` or `userPrincipalName`
