### ISSUE TITLE
ImportError when creating Docker Raspberry

### ISSUE THREAD

**Issue by anemonium** [haiwen/seafile#2119]
Hi There

I made a Dockerimage for my Raspberry Pi 3. Up to Version 6.0.9 everything works fine. When I try to upgrade to Version 6.1 or higher i always get following error, when I start Seafile:

Traceback (most recent call last):
  File "/var/seafile/seafile-server-6.3.1/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/seafile/seafile-server-6.3.1/seahub/thirdpart/Django-1.11.13-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/seafile/seafile-server-6.3.1/seahub/thirdpart/Django-1.11.13-py2.7.egg/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/seafile/seafile-server-6.3.1/seahub/thirdpart/Django-1.11.13-py2.7.egg/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/seafile/seafile-server-6.3.1/seahub/thirdpart/Django-1.11.13-py2.7.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/seafile/seafile-server-6.3.1/seahub/thirdpart/Django-1.11.13-py2.7.egg/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named message

Does anybody else have this problem since trying to upgrade?

**Comment by anemonium** [comment]
Thanks, i'll try that in my dockerfile . how can i exec bash into a container that won't start? the container stops each time because of the error mentioned above.

**Comment by shoeper** [comment]
You have to overwrite the entrypoint in that case to run bash instead of the default entrypoint.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
