### ISSUE TITLE
seaf-cli create 400 bad request

### ISSUE THREAD

**Issue by Redsandro** [haiwen/seafile#2123]
I'm trying `seaf-cli` (for the first time) and I'm getting a  _"HTTP Error 400: Bad Request"_ without much more verbosity.

Any idea what could be wrong?

```
$ seaf-cli create -n test -s https://seafile.example.com -u redsandro
Enter password for user redsandro 

Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 845, in <module>
    main()
  File "/usr/bin/seaf-cli", line 841, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 720, in seaf_create
    token = get_token(url, username, password, conf_dir)
  File "/usr/bin/seaf-cli", line 235, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data)
  File "/usr/bin/seaf-cli", line 208, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

I need to script some basic functions in order to work around certain `seafile-client` issues that make it impossible to do certain tasks:

* https://github.com/haiwen/seafile-client/issues/1123
* https://github.com/haiwen/seafile-client/issues/1132
* https://github.com/haiwen/seafile-client/issues/1135

**Comment by shoeper** [comment]
The details why the request was bad should be available in the server logs.

**Comment by Redsandro** [comment]
I read some old issues which also resulted in 400:

https://github.com/haiwen/seafile/issues/1257#issuecomment-107790202

> I found the problem with my sync command. I wasn't using the right credentials. Sorry for the long post.

https://github.com/haiwen/seafile/issues/237#issuecomment-91821422

> It seems like this kind of error still appears when I put wrong login or password, this is really confusing.

So I tried again using my email address, in quotes, and it works!

## Two problems

### 1.

`seaf-cli` states:

> -u USERNAME, --username USERNAME

This is wrong. Username doesn't work. User email address is required.

### 2. 

The error can be anything. Ideally it should return a sane payload that describes the problem.

---

I'm now educated. However, I suggest addressing these issues, because searching the issues and the forum shows that this has been **confusing users since 2013.**

**Comment by shoeper** [comment]
I don't know what the issue is, but username is the same as email in Seafile and there is no such thing as another username that could get mixed up with it.

**Comment by Redsandro** [comment]
@shoeper you honestly cannot see the confusion? I think you've accumulated 5 years of knowledge and know-how, so it's hard to see with fresh eyes what is confusing.

I can try to explain in more retail, but you have to be open to it.

__1.__ In the approximate period from 1995 to 2015, you would register to forums and websites using a __username__, and activate your account with an __email address__. Internet history has caused these words to be intuitively distinct, and going against this intuition is a bad design pattern.

It is only in the last few years that usernames are becoming deprecated by email addresses. These sites no longer ask for a username; they ask for an email address. The `seaf-cli` asks for a `--username`. This is confusing.

__2.__ If _"username is the same as email in Seafile and there is no such thing as another username that could get mixed up with it,"_ then what is this:

![image](https://user-images.githubusercontent.com/1702193/47598126-f942e500-d997-11e8-83fc-468b69557854.png)

Every day I see this, thinking this must be my username.

__3.__ Same for the web interface:

![image](https://user-images.githubusercontent.com/1702193/47598162-5c347c00-d998-11e8-82d3-e1a7d158e4f5.png)

Which one of these would you think is a _username_, and which one an _email address_?

__4.__ Empirical evidence. My issue. This comment:

>  searching the issues and the forum shows that this has been confusing users since 2013.

**Comment by shoeper** [comment]
> 2. If "username is the same as email in Seafile and there is no such thing as another username that could get mixed up with it," then what is this:

That is just the name given in your profile ...

**Comment by Redsandro** [comment]
> I don't get why someone should think he has to put it in to login somewhere.

I am sorry you can't follow my logic and understand why people have been getting confused by Seafile's misnamed command line argument. 

> That is just the name given in your profile

It is not. The profile 'name' is empty. I'll leave this discussion as it is not productive. Here's something I learned for successful UX design: Practice empiricism, not stubbornism.

**Comment by shoeper** [comment]
I don't see why someone should think he has to login with something he wasn't ever able to login?

But maybe I'm too much from the computer science department. A "username" can be anything and in case of Seafile is an email.

**Comment by Redsandro** [comment]
> I don't see why someone should think he has to login with something he wasn't ever able to login?

They would only have logged in **once before**, perhaps ages ago. Seafile-client stays logged in forever. Humans (not robots) don't tend to memorize how they logged in when time passes.

> A "username" can be anything and in case of Seafile is an email.

You quote verses as if everyone has read the bible. This is not common knowledge. This is actually counter intuitive. Everyone and their mother knows that a username and email are different and distinct things, as evidenced by years of internet history. It has become a convention. It's the established way. Etiquette even. It's a pattern, a practice formed by many precedents.

## Let's take this thing we're using right now; Github

![image](https://user-images.githubusercontent.com/1702193/47657149-d0d20b00-db90-11e8-9840-b7ff53628789.png)

On github, you can literally login using your **username OR email**. They are distinct values. I can log in using either `redsandro`, _or_ my email address. If I couldn't use my username to log in, _it wouldn't ask for_ **username OR email**, it would just ask for **email**, and it would _certainly NOT_ ask for **username**.

## Now let's take Seafile

![image](https://user-images.githubusercontent.com/1702193/47657637-b6e4f800-db91-11e8-982d-a0f03c9728e3.png)

The ancient convention of allowing to log in with either a "**Email _OR_ USERNAME**" seems to be followed here.

As with Github or any other site or app in the universe, I don't remember what email address I used to sign up. Luckily, one of these variables seems to be displayed prominently on the `seafile-applet`:
![image](https://user-images.githubusercontent.com/1702193/47598126-f942e500-d997-11e8-83fc-468b69557854.png)

### Things this is not:

* This is not an email address.
* This is not a name entered on the profile.

### Things it could be

Since it's _not an email address_ and I'm being asked for an email OR USERNAME, according to the years old established convention, it would make sense to conclude that: This. Is. In fact:

* **A username**

So let's enter that.

![image](https://user-images.githubusercontent.com/1702193/47658162-c6b10c00-db92-11e8-93c9-54e5c482a514.png)

Look at the second word in the error message. The error message can be recognized by the red color. __Now they want an *EMAIL*, not a username.__ Perhaps something went wrong with the translations.

We dig up the email from the client options or settings and log in successfully using _email_.

### Let's try `seaf-cli`.

![image](https://user-images.githubusercontent.com/1702193/47658742-ccf3b800-db93-11e8-99e9-7a716b5d0730.png)

It pretty much says "USERNAME" 5 times.

# BUT IT ONLY ACCEPTS AN EMAIL ADDRESS.

## They are not the same thing in any precedent or convention.

### This is confusing.

Whether you "understand" it or not.

**Comment by marcusmysc** [comment]
@Redsandro Just for your info, there is the possibility to login via username if the admin has set it:

<img width="373" alt="bildschirmfoto 2018-10-29 um 16 52 05" src="https://user-images.githubusercontent.com/8075847/47662447-404cf800-db9b-11e8-8d73-7af82001667f.png">

This can be done in CE and pro.

**Comment by Redsandro** [comment]
@marcusmysc thank you, good to know. I do wonder where the (not) username comes from in my account, and I wonder if it should (automatically) be used for login purposes.

**Comment by shoeper** [comment]
@Redsandro I told you where it comes from. If no name has been set in your profile it's the local part of your email address.

**Comment by Redsandro** [comment]
> @Redsandro I told you where it comes from.

I'm afraid you did not. Then you did, but were wrong. Finally - I just figured out - you edited your message after I read it. It's all a bit chaotic.

It might be beneficial to the project to be more open to constructive feedback on the confusing aspects of the applications. You'll be surprised how quickly a new user and potential asset can feel bad about an entire project through the first interactions with its community.

UX is an empirical science more than anything. That's why companies run hundreds of A/B tests on their apps. When someone tells you something is confusing, you don't challenge that.

**Comment by shoeper** [comment]
I cannot change it. I try to help (in the forum, sometimes on github) and I keep the issue tracker clean, but it only is my hobby. (One big issue has always been that the developers can't find the real issues, because there is so much garbage on the issue tracker.)

From my point of view it is very unfortunate that bug fixing has a low priority for the devs. The core used to work quite well, but over the years some bugs have accumulated and have not been fixed. E.g. when the client has an issue with its metadata it cannot recover by itself, synchronization of libraries can break in some corner cases, .... The client (seaf-daemon) also has a memory leak. At the same time new features (and obviously new bugs) are added continuously. I'd rather like to see the core issues fixed before UI details are solved (e.g. I'm pretty sure that more users are effected by corrupt client metadata, than even use seaf-cli).

**Comment by shoeper** [comment]
Not to mention the "new projects" SeaDrive and seafile-docker, which are both alpha at most, but it is neither communicated nor are the issues fixable anytime soon (Dropbox needed more than a year with multiple engineers to implement something like SeaDrive, because it is a HUGE amount of work (it is very performance & security sensitive and to work optimally it has to be integrated in each operating system individually).

Maybe I should completely stop following the project and see if it has improved in two years or something like that.

Btw: Did it work with your email and password or is it still http 400?

**Comment by Redsandro** [comment]
@shoeper thank you for elaborating on this.

> I'd rather like to see the core issues fixed before UI details are solved

This I fully understand. It is however important to acknowledge issues, no matter how you would triage them. (Psychologically speaking it's especially important for new curious users). 

Sounds to me like the devs would be wise to give you the ability to apply certain labels, so you can triage issues. E.g. "UX issue", "Bug", "Critical Bug" etc.

> Did it work with your email and password

Yes, I got it working. I was advocating in the interest of the project for other users who will encounter the same problem.

> Maybe I should completely stop following the project

This was not my intent. Help out where you can and _when you want,_ but don't forget you always have the option to ignore any issues that are not worth your time. When responding to (new) users, read some code of conducts and see if you can identify with any of them. Usually the gist is something like: _"be patient, emphatic and welcoming, or skip the thread."_

I'll split this issue in actionable issues, and close this misunderstanding.

* https://github.com/haiwen/seafile/issues/2124
* https://github.com/haiwen/seafile/issues/2125
* https://github.com/haiwen/seafile/issues/2126

**Comment by shoeper** [comment]
> Sounds to me like the devs would be wise to give you the ability to apply certain labels, so you can triage issues. E.g. "UX issue", "Bug", "Critical Bug" etc.

I can do it for some time now, but don't have the impression that it changes something. There are even some issues I think are important (e.g. docker images use an outdated base image and do not receiver ANY security updates because of that), but most of the time nothing happens (not even an answer).

**Comment by shoeper** [comment]
And yes, I agree sometimes a nicer way would be good. I don't find it too easy to always find the best way.

Maybe ignoring more issues would be better, but it would also lead to more open issues and less overview over the important issues.

**Comment by Redsandro** [comment]
> I can do it for some time now, but don't have the impression that it changes something.

This is not my project, but I would argue that the label usage can be optimized. First thing I would do is drop all the `priority-low` label from issues, and add `priority-high` label to every other issue.

**Comment by shoeper** [comment]
Yes, I agree that label usage could be optimized, but it also takes hours to change it.

**Comment by shoeper** [comment]
Also looks like they took care of the many issues, today. I'm still not sure if some of the important bugs are also being fixed, now. We'll see.

**Comment by flyingtoaster0** [comment]
@Redsandro Thank you very much. 6 years later, using my email address was the answer for me.
