### ISSUE TITLE
400 ("Bad Request") is ambiguous. Use 401 ("Unauthorized") for auth problems.

### ISSUE THREAD

**Issue by Redsandro** [haiwen/seafile#2126]
The server responds with HTTP `400`, leaving people puzzled as to the cause. A `400` is not usually attributed to wrong credentials. This has been confusing [since 2013](https://github.com/haiwen/seafile/issues/237).

Let's use `401` ("Unauthorized") in this case. It communicates the _specific_ issue.

**Comment by freeplant** [comment]
Most API will return 400 only when the argument is wrong. Which APIs return 400 for auth problems?

**Comment by Redsandro** [comment]
@freeplant sorry, I forgot to add an example. It's when using `seaf-cli` to connect to seafile community edition.

```
$ seaf-cli create -n test -s https://seafile.myserver.com -u wrongusename
Enter password for user wrongusename 

Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 845, in <module>
    main()
  File "/usr/bin/seaf-cli", line 841, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 720, in seaf_create
    token = get_token(url, username, password, conf_dir)
  File "/usr/bin/seaf-cli", line 235, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data)
  File "/usr/bin/seaf-cli", line 208, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

Because of the `HTTP Error 400: Bad Request` message, I assumed everything imaginable, _except_ the idea that I may have entered wrong credentials. The latter turned out to be the case. :sweat_smile:
