### ISSUE TITLE
Error running seafile-admin setup: Cannot resolve keyword 'name'

### ISSUE THREAD

**Issue by PedroLuiz99** [haiwen/seafile#2169]
Hello!

I am trying to install the Seafile Server from the source code. The compilation was successful, but when I run the seafile-admin script to setup the server, the following error is displayed:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 288, in emit_post_migrate_signal
    db=db)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/constance/models.py", line 16, in create_perm
    model='config')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 325, in get
    clone = self.filter(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1144, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1030, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1386, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: app_label, id, model, permission
Error: Seahub syncdb failed
```

These are the dependencies that I installed on Python 2.7:
```
captcha (0.3) ------> Installed after some errors on the same script
certifi (2019.3.9)
chardet (3.0.4)
Django (1.8)
django-appconf (1.0.3)
django-compressor (2.2)
django-constance (1.0.1)
django-node (4.0.0)
django-picklefield (1.1.0) ------> Installed after some errors on the same script
django-post-office (3.1.0)
django-statici18n (1.8.2)
django-webpack (3.1.1)  ------> Installed after some errors on the same script
django-webpack-loader (0.6.0)  ------> Installed after some errors on the same script
djangorestframework (3.9.2)
et-xmlfile (1.0.1)
flup (1.0.3)
gunicorn (19.9.0)
idna (2.8)
jdcal (1.4)
jsonfield (2.0.2)
openpyxl (2.6.1)
optional-django (0.1.0)
Pillow (5.4.1)
pip (8.1.1)
python-dateutil (2.8.0)
pytz (2018.9)
rcssmin (1.0.6)
requests (2.21.0)
rjsmin (1.0.12)
setuptools (20.7.0)
six (1.12.0)
urllib3 (1.24.1)
wheel (0.29.0)

```

I'll be grateful if you can help me. =)

**Comment by Xantolee** [comment]
I also counter the same error. Anyone can help me?

**Comment by sumn255** [comment]
the same error.
I compiled and tried to run on Debian on aarch64 cpu.The compilation was successful, and I have install some missing python packages manually. I evne modified some django code to avoid errors. But I can't slove this one.
