### ISSUE TITLE
Memcached and Seahub problem

### ISSUE THREAD

**Issue by vincenzogianfelice** [haiwen/seafile#2180]
Hi. I set the seahub configuration file 'seahub_settings.py' to use memcached. During startup you have the following problems:.
I installed the following packages:

```
pip install pylibmc django django-pylibmc python-memcached
apt-get install memcached libmemacached-dev
```
And here is also the seahub_settings configuration file:

```
# -*- coding: utf-8 -*-
SECRET_KEY = "MYKEY"
FILE_SERVER_ROOT = 'https://192.168.1.81/seafhttp'

THUMBNAIL_ROOT = '/tmp/thumbnails/'
#ENABLE_VIDEO_THUMBNAIL = False
#THUMBNAIL_VIDEO_FRAME_TIME = 5

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'MYEMAIL'
EMAIL_HOST_PASSWORD = 'MYPASSWORD'
EMAIL_PORT = 587

CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': '/var/run/memcached.sock',
    }
}
```
Error log:

```
ServerDown: error 47 from memcached_add: (0x555e5943ed70) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  socket: /var/run/memcached.sock -> libmemcached/connect.cc:720
2019-04-18 20:58:29,606 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:CUR_TOPINFO): Broken pipe
Traceback (most recent call last):
  File "/home/cloudhome/.local/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/cloudhome/cloud/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:CUR_TOPINFO): Broken pipe
2019-04-18 20:58:29,688 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:throttle_user_3): Broken pipe
Traceback (most recent call last):
  File "/home/cloudhome/.local/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/cloudhome/cloud/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:throttle_user_3): Broken pipe
2019-04-18 21:04:48,666 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:throttle_user_3): Broken pipe
Traceback (most recent call last):
  File "/home/cloudhome/.local/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/cloudhome/cloud/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:throttle_user_3): Broken pipe
```

How to resolv?

**Comment by freeplant** [comment]
Please ask the question in our forum https://forum.seafile.com
