### ISSUE TITLE
Error when syncing on new device

### ISSUE THREAD

**Issue by vfricou** [haiwen/seafile#2181]
Hello,

I've an issues on library new sync.

Version :

- Server : 6.2.5
- Agent : 6.1.8

Previously I've a library synced on client, I've delete sync, and when I would to resync it, I get following issue on agent 

```
Failed to get repo download information:
Server Error
```

According, on server the logs display followings error :

```
==> seafile.log <==
[04/18/19 08:06:22] ../common/seaf-db.c(425): Error prepare statement INSERT INTO RepoUserToken VALUES (?, ?, ?): mysql_stmt_prepare failed: Column count doesn't match value count at row 1
.
[04/18/19 08:06:22] repo-mgr.c(1393): failed to add repo token. repo = 53a50f4d-2bbc-4d4f-ade7-f0953dfb815e, email = vincent@fricouv.eu

==> seahub_django_request.log <==
2019-04-18 08:06:22,194 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/repos/53a50f4d-2bbc-4d4f-ade7-f0953dfb815e/download-info/
Traceback (most recent call last):
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/seahub/api2/views.py", line 1231, in get
    return repo_download_info(request, repo_id)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seahub/seahub/api2/views.py", line 432, in repo_download_info
    token = seafile_api.generate_repo_token(repo_id, email)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seafile/lib64/python2.7/site-packages/seaserv/api.py", line 595, in generate_repo_token
    return seafserv_threaded_rpc.generate_repo_token(repo_id, username)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seafile/lib64/python2.7/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/srv/web/branch/seafile/seafile-server-6.2.5/seafile/lib64/python2.7/site-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
SearpcError: DB error
```

**Comment by freeplant** [comment]
Please ask the question in our forum https://forum.seafile.com
