### ISSUE TITLE
CentOS 7.4 - Seafile CE 7.0 - Seahub fails to start with Python error

### ISSUE THREAD

**Issue by arjones85** [haiwen/seafile#2195]
[cloud@main seafile-server-latest]$ ./seahub.sh start

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8000 ...
Traceback (most recent call last):
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.8.1', 'console_scripts', 'gunicorn')()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/arbiter.py", line 60, in __init__
    self.setup(app)
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/cloud/seafile-server-7.0.0/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/cloud/seafile-server-7.0.0/seahub/seahub/__init__.py", line 4, in <module>
    from handlers import repo_created_cb, repo_deleted_cb, clean_up_repo_trash_cb, \
  File "/home/cloud/seafile-server-7.0.0/seahub/seahub/handlers.py", line 25, in <module>
    import seafevents
ImportError: No module named seafevents

Error:Seahub failed to start.
Please try to run "./seahub.sh start" again

**Comment by arjones85** [comment]
This is caused by Seahub looking for the existence of seafevents.conf, as opposed to checking it's a CE server or not.

Removing that config file allowed seahub to launch.
