### ISSUE TITLE
Failed to view file's history

### ISSUE THREAD

**Issue by chatainsim** [haiwen/seafile#2235]
Hello,
When I try to view file's history I have this error in seahub.log:
```
2019-08-22 14:29:07,998 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /repo/file_revisions/aad90043-c7b2-4642-ac2a-180810c586f3/
Traceback (most recent call last):
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/simon/web/easter/seafile-server-7.0.4/seahub/seahub/views/__init__.py", line 862, in file_revisions
    suffix_list = seafevents_api.get_file_history_suffix()
AttributeError: 'NoneType' object has no attribute 'get_file_history_suffix'
```
How can I fix this ?
Thanks

**Comment by freeplant** [comment]
We can't reproduce the problem. It is likely caused by your configuration.

**Comment by chatainsim** [comment]
And how can I fix this issue on my side ?
What does that mean ? Does a table in DB is missing ?
Thanks

**Comment by freeplant** [comment]
Is there a file called seafevents.conf in your conf directory?
