### ISSUE TITLE
seaf-cli version 7.0.2  issues

### ISSUE THREAD

**Issue by rcoss** [haiwen/seafile#2248]
seaf-cli version 7.0.2 fails with any command that tries to connect to a remote seafile server.
client OS: debian 9.11 , python 2.7.13
server:  OS debian 7.11, seafile 6.11, apache
server OS debian 9.9, seafile 6.25, apache
on both servers certificates by Let's Encrypt and valid.
openssl s_client connect server:port and curl -v https://server/seafhttp/protocol-version
give correct results.
Any GUI client is ok with both servers, seaf-cli verion 4.3.2 and seaf-applet 7.0.2 too.
Bugs? found so far:
a) when trying to connect to remote server error is:
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 
Apparently python >= 2.7.9 verifies server certificates by default, but in seaf-cli urllib2.urlopen
does not load any CA cert.
Dirty hack to test it:
replace line 210
resp = urllib2.urlopen(req)
by
resp = urllib2.urlopen(req, cafile="/etc/ssl/certs/ca-certificates.crt")
and now client connects ok.

b) when trying to download/sync a repo eror is:
Traceback (most recent call last):
  File "./myseaf-cli", line 883, in <module>
    main()
  File "./myseaf-cli", line 879, in main
    args.func(args)
  File "./myseaf-cli", line 459, in seaf_download
    repo_salt = tmp['salt']
KeyError: 'salt'

Apparently key salt is not defined for repos in any of both servers
Dirty hack to test it:
replace line 459
repo_salt = tmp['salt']
with
repo_salt = None

and now command download works as expected.

**Comment by rcoss** [comment]
Update:
The first issue mentioned (cert verification) seems to be a problem with python 2.7.13 as shipped with debian 9.11:

Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> 
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile=None, capath='/usr/local/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/local/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/local/ssl/certs')
>>>

But default capath on debian 9.11 is /etc/ssl/certs
