### ISSUE TITLE
seaf-cli status not working wenn Downloads are done

### ISSUE THREAD

**Issue by HoffmannP** [haiwen/seafile#2269]
status worked while downloading. After it was done I could only get

```
$USER@$HOST:~/Seafile/$FOLDER$ seaf-cli status
# Name                                              	Status              	Progress            
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 905, in <module>
    main()
  File "/usr/bin/seaf-cli", line 901, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 718, in seaf_status
    if not task:
  File "/usr/lib/python2.7/dist-packages/future/types/newobject.py", line 88, in __nonzero__
    return type(self).__bool__(self)
AttributeError: type object '_SearpcObj' has no attribute '__bool__'
```

**Comment by killing** [comment]
With the latest version this should work now.
