### ISSUE TITLE
Seafdav XML issue

### ISSUE THREAD

**Issue by chatainsim** [haiwen/seafile#2312]
Hello,
I have some issue in the seafdav.log:

`[2020-02-29 23:19:09,147]:  ErrorPrinter: caught Exception
[2020-02-29 23:19:09,148]:  Traceback (most recent call last):
  File "/home/simon/web/easter/seafile-server-latest/seahub/thirdpart/wsgidav/error_printer.py", line 43, in __call__
    for v in app_iter:
  File "/home/simon/web/easter/seafile-server-latest/seahub/thirdpart/wsgidav/request_resolver.py", line 201, in __call__
    for v in app_iter:
  File "/home/simon/web/easter/seafile-server-latest/seahub/thirdpart/wsgidav/request_server.py", line 113, in __call__
    app_iter = method(environ, start_response)
  File "/home/simon/web/easter/seafile-server-latest/seahub/thirdpart/wsgidav/request_server.py", line 327, in doPROPFIND
    util.addPropertyResponse(multistatusEL, href, propList)
  File "/home/simon/web/easter/seafile-server-latest/seahub/thirdpart/wsgidav/util.py", line 849, in addPropertyResponse
    etree.SubElement(propEL, name).text = toUnicode(value)
  File "src/lxml/etree.pyx", line 1020, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
`
Do you know how to solve this issue ?

Thanks

**Comment by chatainsim** [comment]
I'm using seafile-server-7.0.5

**Comment by killing** [comment]
The wsgidav code used in 7.0 series may have some bugs. Please upgrade to 7.1 version to check whether the issue is fixed. But you still need to wait a few days until 7.1.2 is released, which is more stable.

**Comment by chatainsim** [comment]
Thanks, I'll wait a little longer to grab the 7.1.2.
