### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by cr0c0dylus** [haiwen/seafile#2327]
After update to 7.1.3 my seahub.log is full of UnicodeDecodeError errors:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)
2020-04-27 08:18:51,260 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/seahub/views/__init__.py", line 1160, in react_fake_view
    'custom_nav_items' : json.dumps(CUSTOM_NAV_ITEMS),
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/template/base.py", line 205, in render
    with context.bind_template(self):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/template/context.py", line 263, in bind_template
    updates.update(processor(self.request))
  File "/home/seafile/server/seafile-server-7.1.3/seahub/seahub/base/context_processors.py", line 93, in base
    avatar_url, is_default, date_uploaded = api_avatar_url(username, 72)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/seahub/avatar/util.py", line 42, in cached_func
    return cache.get(key) or cache_set(key, func(user, size))
  File "/usr/local/lib/python3.6/dist-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/seafile/server/seafile-server-7.1.3/seahub/thirdpart/django/core/cache/backends/memcached.py", line 79, in get
    val = self._cache.get(key)

**Comment by woffs** [comment]
I had to delete the django cache (filebased `/tmp/seahub_cache/` in my case) after upgrading from seafile 6 to seafile 7 to solve this. Your cache is memcache, maybe the solution is similar.
