### ISSUE TITLE
Compile new translations results in missing path for seahub/frontend/build

### ISSUE THREAD

**Issue by Radapompa** [haiwen/seafile#2338]
I've recently updated Swedish translations and wanted to try them out. I noticed there is a new way for compiling the translations after editing them according to this page: https://download.seafile.com/published/seafile-manual/develop/translation.md

On step 5 you're supposed to run these commands in the seafile-server-lastest directory
./seahub.sh python-env python3 seahub/manage.py compilejsi18n -l <lang-code>
./seahub.sh python-env python3 seahub/manage.py collectstatic --noinput -i admin -i termsandconditions --no-post-process

First command works fine (changing <lang-code> to sv). The second command returns following error:
./seahub.sh python-env python3 seahub/manage.py collectstatic --noinput -i admin -i termsandconditions --no-post-process

LC_ALL is not set in ENV, set to en_US.UTF-8
Copying '/opt/seafile/seafile-server-7.1.4/seahub/static/scripts/i18n/sv/djangojs.js'
Traceback (most recent call last):
  File "seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/files/storage.py", line 397, in listdir
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/seafile/seafile-server-7.1.4/seahub/frontend/build'
Done.

I can't seem to find the file or folder seahub/frontend/build when checking manually aswell. Is there an issue with the language I choose or is there something else? I don't see any issues with the translations after running the command.

**Comment by freeplant** [comment]
Has been fixed in https://github.com/haiwen/seafile-admin-docs/pull/254/files
