### ISSUE TITLE
Linux CLI cannot download or sync

### ISSUE THREAD

**Issue by Antoninum** [haiwen/seafile#237]
Hi,

I tried to test seafile client on my debian 6.0 "Squeeze". The only available client that I found is the linux CLI.

When I try to dowload my library (from seacloud), I get the following error : 

```
Traceback (most recent call last):
  File "/home/user/Tools/seafile-cli-1.6.1/bin/seaf-cli.py", line 630, in <module>
    main()
  File "/home/user/Tools/seafile-cli-1.6.1/bin/seaf-cli.py", line 626, in main
    args.func(args)
  File "/home/user/Tools/seafile-cli-1.6.1/bin/seaf-cli.py", line 423, in seaf_sync
    token = get_token(url, username, password)
  File "/home/user/Tools/seafile-cli-1.6.1/bin/seaf-cli.py", line 177, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data)
  File "/home/user/Tools/seafile-cli-1.6.1/bin/seaf-cli.py", line 171, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: BAD REQUEST
```

I downloaded the 1.6.1 version (64bits).
My python version is 2.6.6
The argparse module is installed

I performed the following recommended steps :
    `cd /home/user/Tools/seafile-cli-1.6.1/`
    `mkdir ~/seafile-client`
    `./seaf-cli init -d ~/seafile-client`
    `./seaf-cli start`
    `sudo ln -s `readlink -f seaf-cli` /usr/bin/`
    `seaf-cli download -l 4da3f13b-ae1b-4793-afd9-************ -s https://seacloud.cc -d /home/user/path/to/empty/folder/ -u my@email.com`

My password is asked, and then I get the error.
The same happens with the `seaf-cli sync` command.
Nothing is logged in ~/.ccnet/logs/seafile.log or ~/.ccnet/logs/seafile.log when I execute the `seaf-cli download` command.

I tried with the seafile-cli 1.5.3 version with the same result.

What am I missing ?

**Comment by Mucka** [comment]
It seems like this kind of error still appears when I put wrong login or password, this is really confusing.

**Comment by awikatchikaen** [comment]
Same here with last version
