### ISSUE TITLE
Seahub startup issue when trying to start seafile server

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#2382]
Every time I type './seahub.sh start, it gives me this problem.

Starting seahub at port 8000 ...
Traceback (most recent call last):
  File "/media/pi/Cloud/seafile-server-7.1.4/check_init_admin.py", line 351, in <module>
    rpc = RPC()
  File "/media/pi/Cloud/seafile-server-7.1.4/check_init_admin.py", line 284, in __init__
    import ccnet
ModuleNotFoundError: No module named 'ccnet'

How do I go about fixing this issue? Thanks!

**Comment by laur89** [comment]
How was the service installed? Are you using the seafile-provided Docker? Any particular guide that was followed?

**Comment by AlmightyAug** [comment]
The service was installed on Raspberry Pi 4 8GB (installed the Raspberry Pi version of Seafile, and followed this guide here: https://download.seafile.com/published/seafile-manual/deploy/using_sqlite.md

**Comment by Gustl22** [comment]
@AlmightyAug  Does this error still occur, it may be fixed in the latest builds (?)
https://github.com/haiwen/seafile-server/blob/master/ci/run.py#L57

**Comment by AlmightyAug** [comment]
I haven't tried it yet. I will try it when I get physical access to my linux box.

Thanks for informing me
