### ISSUE TITLE
[seaf-cli] library download fails - no socket

### ISSUE THREAD

**Issue by laur89** [haiwen/seafile#2383]
Debian testing, Linux WH5005264 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
    seafile-cli: 7.0.8-2
    server: 7.1.5

Title says it all - trying to download a library results in an error.

**Repro:**
**init seafile client:**

    seaf-cli init -c "$HOME/.ccnet" -d "/data"

Note:
- $HOME/.ccnet/ is created
- /data/seafile-data/ is created

**download **library:****

    seaf-cli download-by-name --libraryname main -s 'https://my.seafile.domain' -u my.mail@example.com -p 'mypasswd'

Results in following exception:

	New device id created
	Starting to download ...
	Library library-uuid-redacted will be downloaded to /data/seafile
	Traceback (most recent call last):
	File "/usr/lib/python3/dist-packages/pysearpc/named_pipe.py", line 88, in _get_transport
		transport = self._pool.get(False)
	File "/usr/lib/python3.8/queue.py", line 167, in get
		raise Empty
	_queue.Empty

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	File "/usr/bin/seaf-cli", line 983, in <module>
		main()
	File "/usr/bin/seaf-cli", line 979, in main
		args.func(args)
	File "/usr/bin/seaf-cli", line 594, in seaf_download_by_name
		seaf_download(args)
	File "/usr/bin/seaf-cli", line 530, in seaf_download
		seafile_rpc.download(repo,
	File "/usr/lib/python3/dist-packages/pysearpc/client.py", line 126, in newfunc
		ret_str = self.call_remote_func_sync(fcall_str)
	File "/usr/lib/python3/dist-packages/pysearpc/named_pipe.py", line 100, in call_remote_func_sync
		transport = self._get_transport()
	File "/usr/lib/python3/dist-packages/pysearpc/named_pipe.py", line 90, in _get_transport
		transport = self._create_transport()
	File "/usr/lib/python3/dist-packages/pysearpc/named_pipe.py", line 83, in _create_transport
		transport.connect()
	File "/usr/lib/python3/dist-packages/pysearpc/named_pipe.py", line 47, in connect
		self.pipe.connect(self.socket_path)
	FileNotFoundError: [Errno 2] No such file or directory

Note line 47 in `/usr/lib/python3/dist-packages/pysearpc/named_pipe.py` is `self.pipe.connect(self.socket_path)`.
`self.socket_path` value at that point is `/data/seafile-data/seafile.sock`, but `/data/seafile-data` only contains one file named `id`

**Comment by laur89** [comment]
Any input on this?

**Comment by killing** [comment]
Have you started the client with "seaf-cli start"?

**Comment by laur89** [comment]
So that needs to be done before the very first initialization?

**Comment by killing** [comment]
You need to start the client daemon first before initiating a download.
