### ISSUE TITLE
Error when starting up seafile from docker-compose(upgrade script issue)

### ISSUE THREAD

**Issue by walteraa** [haiwen/seafile#2385]
Hey folks,

I was trying to start seafile from docker-compose and I am getting a error in the upgrade script as you can see in the log below:
```
seafile      | *** Running /etc/my_init.d/01_create_data_links.sh...
seafile      | *** Booting runit daemon...
seafile      | *** Runit started as PID 24
seafile      | *** Running /scripts/start.py...
seafile      | [10/26/2020 15:13:58][upgrade]: Running script /opt/seafile/seafile-server-7.1.5/upgrade/upgrade_6.3_7.0.sh
seafile      | 
seafile      | -------------------------------------------------------------
seafile      | This script would upgrade your seafile server from 6.3 to 7.0
seafile      | Press [ENTER] to contiune
seafile      | -------------------------------------------------------------
seafile      | 
seafile      | 
seafile      | Can't find a python executable of version 2.7 or above in PATH
seafile      | Install python 2.7+ before continue.
seafile      | Or if you installed it in a non-standard PATH, set the PYTHON enviroment varirable to it
seafile      | 
seafile      | [2020-10-26 15:13:58] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
seafile      | [2020-10-26 15:13:58] Running scripts /opt/seafile/seafile-server-7.1.5/upgrade/upgrade_6.3_7.0.sh
seafile      | Traceback (most recent call last):
seafile      |   File "/scripts/start.py", line 86, in <module>
seafile      |     main()
seafile      |   File "/scripts/start.py", line 58, in main
seafile      |     check_upgrade()
seafile      |   File "/scripts/upgrade.py", line 182, in check_upgrade
seafile      |     run_script_and_update_version_stamp(script, new_version)
seafile      |   File "/scripts/upgrade.py", line 61, in run_script_and_update_version_stamp
seafile      |     call(script)
seafile      |   File "/scripts/utils/__init__.py", line 70, in call
seafile      |     return subprocess.check_call(*a, **kw)
seafile      |   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
seafile      |     raise CalledProcessError(retcode, cmd)
seafile      | subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-7.1.5/upgrade/upgrade_6.3_7.0.sh' returned non-zero exit status 1.
seafile      | *** /scripts/start.py exited with status 1.
seafile      | *** Shutting down runit daemon (PID 24)...
seafile      | *** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
seafile      | *** Killing all processes...
seafile exited with code 1
```

I am using the default `docker-compose.yml` file provided in the documentation. Does anyone know how to fix this?

**Comment by laur89** [comment]
Looks like you're trying to upgrade from v6 to 7.0 using 7.1.5 runtime;
7.1.5 no longer supports python 2, so I'd suggest running same upgrade script from seafile-server-7.1.0 (as opposed to from 7.1.5)

**Comment by TobiasReichert** [comment]
I can confirm this fix.
I had an old docker seafile instance in version 6.3.
With version 7.0.5 I could update without errors and after that I could also update to latest. 
Thanks for the information.

**Comment by walteraa** [comment]
Thank you very much, guys!!! It solved the issue. Closing this issue :smile:
