### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by kotori2** [haiwen/seafile#2390]
Fresh installation with https://github.com/haiwen/seafile-server-installer on Ubuntu 20.04.
```
$ sudo ./seahub.sh start-fastcgi

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.0/seahub/seahub/avatar/models.py", line 23, in <module>
    from PIL import Image
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/PIL/Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.0/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.0/seahub/seahub/avatar/models.py", line 26, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
^C
```

**Comment by kotori2** [comment]
removing `/opt/seafile/seafile-server-7.1.0/seahub/thirdpart/PIL` and use system-provided PIL works for me.

**Comment by killing** [comment]
Hi you should not start seahub with "start-fastcgi". fastcgi is no longer supported. Please use "start" command.

BTW, please first post usage questions to the forum, instead of Github.
