### ISSUE TITLE
Upgrade from 7.1 to 8.0 fails because of broken upgrade SQL

### ISSUE THREAD

**Issue by APz** [haiwen/seafile#2415]
I upgraded from 7.1.5 to 8.0.1 on a system that uses SQLite backend. 

The upgrade fails the following way:

`Updating seafile/seahub database ...

[INFO] You are using SQLite3
[INFO] updating seahub database...
Traceback (most recent call last):
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 384, in <module>
    main()
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 379, in main
    db_updater.update_db()
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 275, in update_db
    super(SQLiteDBUpdater, self).update_db()
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 129, in update_db
    self.update_seahub_sql(seahub_sql)
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 299, in update_seahub_sql
    self.apply_sqls(self.seahub_db, sql_path)
  File "/opt/13th/seafile-server-8.0.1/upgrade/db_update_helper.py", line 289, in apply_sqls
    conn.execute(line)
sqlite3.OperationalError: no such table: VirusFile

Failed to upgrade your database`

I investigated the SQL script that gets run and this problem happens because 7.1.5 does not have a table called VirusFile, yet the script attempts to blindly migrate data off it. Since the table gets completely recreated as a part of the migration, I experimented by removing these 3 lines from the script:

`ALTER TABLE "VirusFile" RENAME TO "VirusFile_old";
INSERT INTO "VirusFile" ("vid", "repo_id", "commit_id", "file_path", "has_deleted") SELECT "vid", "repo_id", "commit_id", "file_path", "has_handle" FROM "VirusFile_old";
DROP TABLE "VirusFile_old"`

This resulted in a working system with the VirusFile table existing, but naturally without any content.

**Comment by feiniks** [comment]
Yes, you're right.The VirusFile table isn't existing in CE.We will fix this error later.
