### ISSUE TITLE
Error when 2FA enabled and setting a webdav password

### ISSUE THREAD

**Issue by Power2All** [haiwen/seafile#2448]
Server is giving a error when WebDAV secret is set.
Django error log here:

```2021-04-28 22:24:44,655 [ERROR] django.request:228 log_response Internal Server Error: /profile/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.4/seahub/thirdpart/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-8.0.4/seahub/thirdpart/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-server-8.0.4/seahub/thirdpart/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-8.0.4/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-8.0.4/seahub/seahub/profile/views.py", line 82, in edit_profile
    decoded = UserOptions.objects.get_webdav_decoded_secret(username)
  File "/opt/seafile/seafile-server-8.0.4/seahub/seahub/options/models.py", line 268, in get_webdav_decoded_secret
    decoded = aes.decode(secret)
  File "/opt/seafile/seafile-server-8.0.4/seahub/seahub/utils/hasher.py", line 54, in decode
    return DecodeAES(self.cipher, data)
  File "/opt/seafile/seafile-server-8.0.4/seahub/seahub/utils/hasher.py", line 30, in <lambda>
    DecodeAES = lambda c, e: c.decrypt(base64.b64decode(e)).decode('utf-8').rstrip(PADDING)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding```

**Comment by imwhatiam** [comment]
@Power2All 

Hello, are there any special characters in your WebDAV secret? 
Can you change your WebDAV secret to check if this problem still persists for a test?  If Yes, can you send us the test WebDAV secret?

**Comment by AlexVonB** [comment]
```
[ERROR] django.request:222 log_response Internal Server Error: /seafile/api/v2.1/webdav-secret/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/seafile/seafile-server-8.0.7/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-8.0.7/seahub/seahub/api2/endpoints/webdav_secret.py", line 44, in put
    aes = AESPasswordHasher()
  File "/opt/seafile/seafile-server-8.0.7/seahub/seahub/utils/hasher.py", line 39, in __init__
    self.cipher = AES.new(secret.encode('utf-8'), AES.MODE_ECB)
AttributeError: 'NoneType' object has no attribute 'new'
```

**Comment by freeplant** [comment]
Please test again with version 12.0. I think the problem should have already been fixed.
