### ISSUE TITLE
Mariadb Warning

### ISSUE THREAD

**Issue by fearlessxjdx** [haiwen/seafile#2508]
```plain
[Warning] Aborted connection 70 to db: 'seafile_db' user: 'seafile' host: '172.21.21.21' (Got an error reading communication packets)
```
Does this matter? How to fix this? mariadb:10.5

**Comment by killing** [comment]
I think this is just a network error.

**Comment by fearlessxjdx** [comment]
> I think this is just a network error.

But I'm running with docker, the IP address 172.21.21.21 is actually the local machine

**Comment by aymenSo** [comment]
I have the same warning:
`2023-10-27  9:46:46 3358 [Warning] Aborted connection 3358 to db: 'seafile_db' user: 'seafile' host: '172.27.0.2' (Got an error reading communication packets)`
Seafile pro in docker mariaDB v10.7 and Seafile pro v9.0.5

**Comment by RaidOpe** [comment]
same in mine 

`2023-11-26 12:06:13 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets)
2023-11-26 12:06:20 57 [Warning] Aborted connection 57 to db: 'seahub_db' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets)`

and whatever I set  `SEAFILE_ADMIN_EMAIL`  ` SEAFILE_ADMIN_PASSWORD` , then popping up `CSRF verification failed. Request aborted.`

**Comment by heartnn** [comment]
> same in mine
> 
> `2023-11-26 12:06:13 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets) 2023-11-26 12:06:20 57 [Warning] Aborted connection 57 to db: 'seahub_db' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets)`
> 
> and whatever I set `SEAFILE_ADMIN_EMAIL` ` SEAFILE_ADMIN_PASSWORD` , then popping up `CSRF verification failed. Request aborted.`

https://manual.seafile.com/config/seahub_settings_py/

### Security settings

```python
# For security consideration, please set to match the host/domain of your site, e.g., ALLOWED_HOSTS = ['.example.com'].
# Please refer https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts for details.
ALLOWED_HOSTS = ['.myseafile.com']


# Whether to use a secure cookie for the CSRF cookie
# https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-secure
CSRF_COOKIE_SECURE = True

# The value of the SameSite flag on the CSRF cookie
# https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-samesite
CSRF_COOKIE_SAMESITE = 'Strict'

# https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-trusted-origins
CSRF_TRUSTED_ORIGINS = ['https://www.myseafile.com']
```

**Comment by Moosbueffel** [comment]
I have the same problem just installed the current docker "seafile PE 11.0".

Is there no solution in the meantime? Some other things don't work in Browser like open docs, or upload files. Perhaps this is the reason?

` 2024-07-24 20:57:44 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'root' host: '172.24.0.4' (Got an error reading communication packets)
`

```
2024-07-24 20:58:22 12 [Warning] Aborted connection 12 to db: 'seahub_db' user: 'seafile' host: '172.24.0.4' (Got an error reading communication packets)
seafile-mysql | 2024-07-24 20:58:22 16 [Warning] Aborted connection 16 to db: 'seahub_db' user: 'seafile' host: '172.24.0.4' (Got an error reading communication packets)
^CGracefully stopping... (press Ctrl+C again to force)
```


![grafik](https://github.com/user-attachments/assets/a15131aa-3654-4d63-8d1d-b0df08453d89)

**Comment by hydrandt** [comment]
I also see these errors in the log. Moreover, while doing garbage collection (docker), I get several times (seems to be same time as the warning message in mysql container:

```
../../common/seaf-db.c(907): Failed to execute sql REPLACE INTO RepoValidSince (repo_id, timestamp) VALUES ('317520f9-0232-4071-bdae-fbed301d22e9', 1717664255): Lost connection to server during query
```

Docker-compose deployment.

**Comment by fcnjd** [comment]
Same is for me with a freshly setup docker-compose deployment. Seafile 11, MariaDB 10. @killing Can you please re-open this? As a lot of people obviosly do have this problem, this should get seriosly discussed somewhere.

**Comment by D1reW0lf** [comment]
Hi all.

Just to add my "me too" on this.
Just installed Seafile 11.0.15 professional under docker and my log is filled with_

`seafile-mysql          | 2024-10-23 13:56:35 481 [Warning] Aborted connection 481 to db: 'seafile_db' user: 'seafile' host: '172.23.0.8' (Got an error reading communication packets)`

https://github.com/haiwen/seafile/issues/2508#issuecomment-1835479482
 I already have all the settings in here but the problem still remains. 

I don't know if that's why I have so many aborted downloads with a "bad request" error.

**Comment by fengwang** [comment]
Happens again... Would @fearlessxjdx please reopen this issue?

I brought everything up using a docker-compose.yml, worked fine in the first place, and then came across to this issue.


The db log:
```
2024-11-06 11:00:28 5 [Warning] Aborted connection 5 to db: 'ccnet_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 4 [Warning] Aborted connection 4 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 136 [Warning] Aborted connection 136 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 117 [Warning] Aborted connection 117 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 135 [Warning] Aborted connection 135 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 98 [Warning] Aborted connection 98 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 134 [Warning] Aborted connection 134 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 100 [Warning] Aborted connection 100 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 118 [Warning] Aborted connection 118 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 11 [Warning] Aborted connection 11 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 7 [Warning] Aborted connection 7 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 115 [Warning] Aborted connection 115 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 116 [Warning] Aborted connection 116 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 8 [Warning] Aborted connection 8 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 6 [Warning] Aborted connection 6 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:28 99 [Warning] Aborted connection 99 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:33 152 [Warning] Aborted connection 152 to db: 'seafile_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:36 156 [Warning] Aborted connection 156 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)
2024-11-06 11:00:36 158 [Warning] Aborted connection 158 to db: 'seahub_db' user: 'seafile' host: '192.168.64.2' (Got an error reading communication packets)

```
The seafile/seahub log:

```

Starting seahub at port 8000 ...
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/scripts/start.py", line 95, in <module>
    main()
  File "/scripts/start.py", line 81, in main
    call('{} start'.format(get_script('seahub.sh')))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-11.0.5/seahub.sh start' returned non-zero exit status 1.
```

**Comment by faceslog** [comment]
Same issue as everyone, I managed to make a stupid script that restart the seafile docker when it fails after some time but it's not practical ... 

Error in mariadb container:
`2024-10-29 22:08:21 17 [Warning] Aborted connection 17 to db: 'seahub_db' user: 'seafile' host: '172.22.0.4' (Got an error reading communication packets)`

**Comment by SkywalkerSpace** [comment]
For troubleshooting, when there were a lot of `[Warning] Aborted connection ...`, please send the seahub.log, seafile.log, seafevents.log at that moment.

By the way, please make sure docker is the latest version.

**Comment by l4kr** [comment]
> > same in mine
> > `2023-11-26 12:06:13 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets) 2023-11-26 12:06:20 57 [Warning] Aborted connection 57 to db: 'seahub_db' user: 'seafile' host: '192.168.240.4' (Got an error reading communication packets)`
> > and whatever I set `SEAFILE_ADMIN_EMAIL` ` SEAFILE_ADMIN_PASSWORD` , then popping up `CSRF verification failed. Request aborted.`
> 
> https://manual.seafile.com/config/seahub_settings_py/
> ### Security settings
> 
> ```python
> # For security consideration, please set to match the host/domain of your site, e.g., ALLOWED_HOSTS = ['.example.com'].
> # Please refer https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts for details.
> ALLOWED_HOSTS = ['.myseafile.com']
> 
> 
> # Whether to use a secure cookie for the CSRF cookie
> # https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-secure
> CSRF_COOKIE_SECURE = True
> 
> # The value of the SameSite flag on the CSRF cookie
> # https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-samesite
> CSRF_COOKIE_SAMESITE = 'Strict'
> 
> # https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-trusted-origins
> CSRF_TRUSTED_ORIGINS = ['https://www.myseafile.com']
> ```

Link is invalid, opinion rejected.

**Comment by aacebedo** [comment]
same problem for me. using pro 11 image . very annoying as my server is now down

**Comment by SmilesOBrien** [comment]
misery loves company. Just deployed this in my homelab yesterday evening. Worked wonderfully. then this morning, this happens, nothing I try fixes it. I deployed this via the Stacks feature on Portainer.

Seafile container:

`Starting seafile server, please wait ...

Seafile server started

Done.

Starting seahub at port 8000 ...

Error:Seahub failed to start.

Please try to run "./seahub.sh start" again

waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' ([Errno 111] Connection refused)")

Traceback (most recent call last):

  File "/scripts/start.py", line 94, in <module>

    main()

  File "/scripts/start.py", line 80, in main

    call('{} start'.format(get_script('seahub.sh')))

  File "/scripts/utils.py", line 70, in call

    return subprocess.check_call(*a, **kw)

  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-11.0.13/seahub.sh start' returned non-zero exit status 1.`

mySQL container:

`2024-12-01 12:29:14+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB

2024-12-01 12:29:14+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'

2024-12-01 12:29:14+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.10+maria~ubu2204 started.

2024-12-01 12:29:14+00:00 [Note] [Entrypoint]: MariaDB upgrade not required

2024-12-01 12:29:14 0 [Note] Starting MariaDB 10.11.10-MariaDB-ubu2204 source revision 3d0fb150289716ca75cd64d62823cf715ee47646 server_uid Id1MgWPIiqAt2SqZRoJ9ouGDzac= as process 1

2024-12-01 12:29:14 0 [Note] InnoDB: Compressed tables use zlib 1.2.11

2024-12-01 12:29:14 0 [Note] InnoDB: Number of transaction pools: 1

2024-12-01 12:29:14 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions

2024-12-01 12:29:14 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)

2024-12-01 12:29:14 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 1

2024-12-01 12:29:14 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF

2024-12-01 12:29:14 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB

2024-12-01 12:29:14 0 [Note] InnoDB: Completed initialization of buffer pool

2024-12-01 12:29:14 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)

2024-12-01 12:29:14 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=1127218

2024-12-01 12:29:14 0 [Note] InnoDB: End of log at LSN=2229016

2024-12-01 12:29:14 0 [Note] InnoDB: To recover: 200 pages

2024-12-01 12:29:14 0 [Note] InnoDB: 128 rollback segments are active.

2024-12-01 12:29:14 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"

2024-12-01 12:29:14 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...

2024-12-01 12:29:14 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.

2024-12-01 12:29:14 0 [Note] InnoDB: log sequence number 2229016; transaction id 4587

2024-12-01 12:29:14 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool

2024-12-01 12:29:14 0 [Note] Plugin 'FEEDBACK' is disabled.

2024-12-01 12:29:14 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.

2024-12-01 12:29:14 0 [Note] Server socket created on IP: '0.0.0.0'.

2024-12-01 12:29:14 0 [Note] Server socket created on IP: '::'.

2024-12-01 12:29:14 0 [Note] mariadbd: ready for connections.

Version: '10.11.10-MariaDB-ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

2024-12-01 12:29:14 0 [Note] InnoDB: Buffer pool(s) load completed at 241201 12:29:14

2024-12-01 12:29:19 6 [Warning] Aborted connection 6 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 25 [Warning] Aborted connection 25 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 26 [Warning] Aborted connection 26 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 27 [Warning] Aborted connection 27 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 28 [Warning] Aborted connection 28 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 43 [Warning] Aborted connection 43 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 44 [Warning] Aborted connection 44 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 45 [Warning] Aborted connection 45 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 15:29:19 46 [Warning] Aborted connection 46 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 5 [Warning] Aborted connection 5 to db: 'ccnet_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 4 [Warning] Aborted connection 4 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 82 [Warning] Aborted connection 82 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 80 [Warning] Aborted connection 80 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 64 [Warning] Aborted connection 64 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 63 [Warning] Aborted connection 63 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 62 [Warning] Aborted connection 62 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 79 [Warning] Aborted connection 79 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 81 [Warning] Aborted connection 81 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 10 [Warning] Aborted connection 10 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 8 [Warning] Aborted connection 8 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 7 [Warning] Aborted connection 7 to db: 'seafile_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 61 [Warning] Aborted connection 61 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 11 [Warning] Aborted connection 11 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)

2024-12-01 17:09:23 9 [Warning] Aborted connection 9 to db: 'seahub_db' user: 'seafile' host: '172.22.0.2' (Got an error reading communication packets)`

**Comment by KeenMaron** [comment]
any updates? got this issue too

**Comment by aacebedo** [comment]
Solved the issue by mounting /opt/seafile/pids to tmpfs in the container. The problem of seahub not starting was coming from the pid files, not from the DB.

The tmpfs is destroyed at each container restart so pids state is correct after the container starts.

**Comment by D1reW0lf** [comment]
But do you still have the DB connection errors?

**Comment by aacebedo** [comment]
> @aacebedo , But do you still have the DB connection errors? 

yes. but I think it comes from the restart and the fact seahub does not close correctly the connection.
at least starting the container succeeds now every time.

**Comment by SmilesOBrien** [comment]
My issue went away on its own. No idea why. Maybe some kind of update? Had the containers offline for a while while I troubleshooted an unrelated issue with my server, and when I started them again everything was fine

**Comment by freeplant** [comment]
I will close the issue, because it contains many different causes for the same "Mariadb Warning". Some already fixed in the latest release.

If anyone still have the problem with version 12.0, just open a new issue.

**Comment by kristianvmd** [comment]
> I will close the issue, because it contains many different causes for the same "Mariadb Warning". Some already fixed in the latest release.
> 
> If anyone still have the problem with version 12.0, just open a new issue.


```
2025-02-13  2:42:55 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2025-02-13  2:42:55 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2025-02-13  2:42:55 0 [Note] InnoDB: Completed initialization of buffer pool
2025-02-13  2:42:55 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
2025-02-13  2:42:55 0 [Note] InnoDB: End of log at LSN=46862
2025-02-13  2:42:55 0 [Note] InnoDB: 128 rollback segments are active.
2025-02-13  2:42:55 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2025-02-13  2:42:55 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2025-02-13  2:42:55 0 [Note] InnoDB: log sequence number 46862; transaction id 14
2025-02-13  2:42:55 0 [Note] Plugin 'FEEDBACK' is disabled.
2025-02-13  2:42:55 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2025-02-13  2:42:55 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2025-02-13  2:42:55 0 [Note] InnoDB: Buffer pool(s) load completed at 250213  2:42:55
2025-02-13  2:42:55 0 [Note] Server socket created on IP: '0.0.0.0'.
2025-02-13  2:42:55 0 [Note] Server socket created on IP: '::'.
2025-02-13  2:42:56 0 [Note] mariadbd: ready for connections.
Version: '10.11.8-MariaDB-ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2025-02-13  2:51:08 12 [Warning] Aborted connection 12 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  2:51:09 13 [Warning] Aborted connection 13 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  2:51:18 16 [Warning] Aborted connection 16 to db: 'unconnected' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  2:52:43 25 [Warning] Aborted connection 25 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 23 [Warning] Aborted connection 23 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 21 [Warning] Aborted connection 21 to db: 'ccnet_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 22 [Warning] Aborted connection 22 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 27 [Warning] Aborted connection 27 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 30 [Warning] Aborted connection 30 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 29 [Warning] Aborted connection 29 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:02 28 [Warning] Aborted connection 28 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:20 42 [Warning] Aborted connection 42 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 38 [Warning] Aborted connection 38 to db: 'ccnet_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 39 [Warning] Aborted connection 39 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 40 [Warning] Aborted connection 40 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 46 [Warning] Aborted connection 46 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 45 [Warning] Aborted connection 45 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 44 [Warning] Aborted connection 44 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:28 43 [Warning] Aborted connection 43 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:05:38 51 [Warning] Aborted connection 51 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 55 [Warning] Aborted connection 55 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 48 [Warning] Aborted connection 48 to db: 'ccnet_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 49 [Warning] Aborted connection 49 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 50 [Warning] Aborted connection 50 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 54 [Warning] Aborted connection 54 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 53 [Warning] Aborted connection 53 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 52 [Warning] Aborted connection 52 to db: 'seafile_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
2025-02-13  3:23:57 56 [Warning] Aborted connection 56 to db: 'seahub_db' user: 'seafile' host: '172.18.0.3' (Got an error reading communication packets)
```

I have the same problem, version 12.
  docker.seafile.top/seafileltd/seafile-pro-mc:12.0-latest

**Comment by neiaberau** [comment]
same here, new setup seafile 12

root@sn2:/srv3/sftest# docker compose logs | tail -10
seafile-mysql  | 2025-02-25 17:27:46 7443 [Warning] Aborted connection 7443 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 17:27:46 8574 [Warning] Aborted connection 8574 to db: 'seafile_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 8949 [Warning] Aborted connection 8949 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 8950 [Warning] Aborted connection 8950 to db: 'seafile_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 8951 [Warning] Aborted connection 8951 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 9323 [Warning] Aborted connection 9323 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 9324 [Warning] Aborted connection 9324 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 9325 [Warning] Aborted connection 9325 to db: 'seafile_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 9699 [Warning] Aborted connection 9699 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)
seafile-mysql  | 2025-02-25 19:27:46 9326 [Warning] Aborted connection 9326 to db: 'seahub_db' user: 'seafile' host: '172.23.0.6' (Got an error reading communication packets)

**Comment by freeplant** [comment]
This is because some code in Seafile server does not close connection to MySQL and the process exit. We will investigate it when we have time. It does not affect the function of Seafile server.

**Comment by jinlin-teck** [comment]
mark一下，看什么时候能解决，总是这个烦人的日志淹没了正常日志。

**Comment by webysther** [comment]
This is not a issue is a new behavior on mariadb > 10.2.24. Just start the container like this:

```yml
image: mariadb:11.4
container_name: db-mariadb-drive
command:
  - '--skip-performance-schema'
  - '--thread_cache_size=0'
  - '--host_cache_size=0'
  - '--skip-external-locking'
  - '--skip-log-bin'
  - '--log-warnings=1'
```

The log_warnings is now 2, just change to use 1 again.

I also confirm the seafile works on mariadb 11.4 (please only use [LTS](https://mariadb.com/kb/en/mariadb-server-release-dates/) and check this [EOL](https://endoflife.date/mariadb))

@freeplant I recomend to update the docs about this.

**Comment by neiaberau** [comment]
I disagree, disabling warning logging instead of fixing the issue is never a good idea

Besides, when this is done, other warnings are also disabled. 
I really advocate for still beeing able to seeing access denied warnings

from the mariadb doc:

> log_warnings >= 2
Access denied errors.
Connections aborted or closed due to errors or timeouts.
Table handler errors
Messages related to the files used to [persist replication state](https://mariadb.com/kb/en/change-master-to/#option-persistence):
Either the default master.info file or the file that is configured by the [master_info_file](https://mariadb.com/kb/en/mariadbd-options/#-master-info-file) option.
Either the default relay-log.info file or the file that is configured by the [relay_log_info_file](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#relay_log_info_file) system variable.
Information about a master's [binary log dump thread](https://mariadb.com/kb/en/replication-threads/#binary-log-dump-thread).

>

**Comment by webysther** [comment]
> I disagree, disabling warning logging instead of fixing the issue is never a good idea
> 
> Besides, when this is done, other warnings are also disabled. I really advocate for still beeing able to seeing access denied warnings
> 
> from the mariadb doc:
> 
> > log_warnings >= 2
> > Access denied errors.
> > Connections aborted or closed due to errors or timeouts.
> > Table handler errors
> > Messages related to the files used to [persist replication state](https://mariadb.com/kb/en/change-master-to/#option-persistence):
> > Either the default master.info file or the file that is configured by the [master_info_file](https://mariadb.com/kb/en/mariadbd-options/#-master-info-file) option.
> > Either the default relay-log.info file or the file that is configured by the [relay_log_info_file](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#relay_log_info_file) system variable.
> > Information about a master's [binary log dump thread](https://mariadb.com/kb/en/replication-threads/#binary-log-dump-thread).
> 
> >

This is not a seafile problem, the mariadb expand the warning level by default, this not change nothing in practice...
