### ISSUE TITLE
Error creating new library

### ISSUE THREAD

**Issue by KuhniBert** [haiwen/seafile#2529]
Hey Everyone,
 
Everytime I try to create an new Library I receive an Error within the Browser (Message:"Error").

The library will still be created but within the logs I receive the following Information:

```
Traceback (most recent call last):
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/seahub/api2/views.py", line 994, in post
    repo_created.send(sender=None,
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/seahub/handlers.py", line 46, in repo_created_cb
    seafevents.save_user_activity(session, record)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/pro/python/seafevents/events/db.py", line 170, in save_user_activity
    session.commit()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1406, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 820, in commit
    self._prepare_impl()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 799, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3224, in flush
    self._flush(objects)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3364, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3324, in _flush
    flush_context.execute()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 627, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1219, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Docker/Seafile/seafile-pro-server-9.0.3/seahub/thirdpart/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1364, "Field 'id' doesn't have a default value")
[SQL: INSERT INTO `Activity` (op_type, op_user, obj_type, timestamp, repo_id, commit_id, path, detail) VALUES (%(op_type)s, %(op_user)s, %(obj_type)s, %(timestamp)s, %(repo_id)s, %(commit_id)s, %(path)s, %(detail)s)]
[parameters: {'op_type': 'create', 'op_user': 'my.mail@some.address.de', 'obj_type': 'repo', 'timestamp': datetime.datetime(2022, 1, 14, 17, 23, 11, 618089), 'repo_id': '56576756-b4c6-43ae-8dee-0bbc8801647e', 'commit_id': None, 'path': '/', 'detail': '{"repo_name": "test234"}'}]
```

Background Information:

java-17-openjdk
elasticsearch:7.16.2
mysql  Ver 15.1 Distrib 10.6.5-MariaDB
seafile-pro-server-9.0.3

Arch 5.15.6-arch2-1
AMD Ryzen 9 3900X
Mem 64 GB ECC
Some SSDs/HDDs

Do you know about the problem and have already a solution?

Would be great if you are already aware of it.
If you need some more information let me know.

Thanks in advance!

**Comment by killing** [comment]
Hi,

This is most likely a configuration issue. Please re-post on our forum for usage questions.
