### ISSUE TITLE
[9.0.2] - Share Link password protect error

### ISSUE THREAD

**Issue by PandaBLN** [haiwen/seafile#2541]
If you try to create a share link with any password you get an error in the WebUI.

seahub.log

2022-01-29 08:11:32,179 [ERROR] django.request:224 log_response Internal Server Error: /api/v2.1/share-links/
Traceback (most recent call last):
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/cloud/seafile-server-9.0.2/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/cloud/seafile-server-9.0.2/seahub/seahub/api2/endpoints/share_links.py", line 419, in post
    fs = FileShare.objects.create_dir_link(username, repo_id, path,
  File "/home/cloud/seafile-server-9.0.2/seahub/seahub/share/models.py", line 173, in create_dir_link
    return self._add_file_share(username, repo_id, path, 'd', password,
  File "/home/cloud/seafile-server-9.0.2/seahub/seahub/share/models.py", line 110, in _add_file_share
    password_enc = make_password(password)
  File "/home/cloud/seafile-server-9.0.2/seahub/seahub/share/models.py", line 31, in make_password
    aes = AESPasswordHasher()
  File "/home/cloud/seafile-server-9.0.2/seahub/seahub/utils/hasher.py", line 39, in __init__
    self.cipher = AES.new(secret.encode('utf-8'), AES.MODE_ECB)
AttributeError: 'NoneType' object has no attribute 'new'

**Comment by PandaBLN** [comment]
Install the -> pip3 install pycryptodome==3.12.0 -> Fix the Problem
https://forum.seafile.com/t/seafile-community-edition-9-0-2-is-ready/15569
