### ISSUE TITLE
Error when downloading ZIP file with new GO fileserver (TypeError for JSON object in query_zip_progress.py)

### ISSUE THREAD

**Issue by marco-websource** [haiwen/seafile#2564]
Hi

We upgraded to Seafile 9.0.4 and noticed the following problem when the new GO fileserver is enabled: When downloading a folder from Seahub there is an error when the ZIP file is created. It seems to be related to the API that returns the progress on the creation of the ZIP file. When using the traditional fileserver (not GO) it works as expected.

Here ist the log and stacktrace of the error (seahub.log):
```
2022-04-15 16:37:04,211 [ERROR] django.request:230 log_response Internal Server Error: /api/v2.1/query-zip-progress/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/seafile/seafile-server-9.0.4/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-9.0.4/seahub/seahub/api2/endpoints/query_zip_progress.py", line 38, in get
    return Response(json.loads(progress))
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
Thanks, Marco

**Comment by killing** [comment]
This should have been fixed in 9.0.5 version.
