### ISSUE TITLE
Bug: Error when logging in with keycloak 20

### ISSUE THREAD

**Issue by ykorzikowski** [haiwen/seafile#2621]
Error happens, when I try to use single-sign-on. The Keycloak-Auth is working, but during callback there is an error. Looks like it happens when seafile is calling the userinfo-api. 

- Keycloak 20
- Seafile Server 9.0.5

![grafik](https://user-images.githubusercontent.com/20556547/202428347-0541d4c1-038f-43f0-9e72-84e6fcdbee33.png)

```

2022-11-17 10:55:52,387 [INFO] seahub.oauth.views:156 format_user_info user info resp:
2022-11-17 10:55:52,387 [ERROR] django.request:224 log_response Internal Server Error: /oauth/callback/
Traceback (most recent call last):
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 87, in _decorated
    return func(request)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 177, in oauth_callback
    user_info, error = format_user_info(user_info_resp)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 159, in format_user_info
    user_info_json = user_info_resp.json()
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

```

**Comment by ykorzikowski** [comment]
Re-Opened in Seahub repo: 

https://github.com/haiwen/seahub/issues/5311
