### ISSUE TITLE
DAVError: (500, 'Concurrent update')

### ISSUE THREAD

**Issue by ykorzikowski** [haiwen/seafile#2704]
Happened after setting up Obsidian remotely save with seafile: 

https://github.com/remotely-save/remotely-save

Unfortunately not usable :(

```
09:21:58.887 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 439, in create_empty_resource
    seafile_api.post_empty_file(self.repo.id, self.rel_path, name, self.username)
  File "/haiwen/seafile-server-10.0.1/seafile/lib/python3/site-packages/seaserv/api.py", line 285, in post_empty_file
    return seafserv_threaded_rpc.post_empty_file(repo_id, parent_dir,
  File "/haiwen/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 127, in newfunc
    return fret(ret_str)
  File "/haiwen/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 11, in _fret_int
    raise SearpcError(dicts['err_msg'])
pysearpc.common.SearpcError: Concurrent update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/error_printer.py", line 50, in __call__
    for v in app_iter:
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_resolver.py", line 224, in __call__
    for v in app_iter:
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 127, in __call__
    app_iter = provider.custom_request_handler(environ, start_response, method)
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/dav_provider.py", line 1594, in custom_request_handler
    return default_handler(environ, start_response)
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 787, in do_PUT
    res = parentRes.create_empty_resource(util.get_uri_name(path))
  File "/haiwen/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 444, in create_empty_resource
    raise DAVError(HTTP_INTERNAL_ERROR, e.msg)
wsgidav.dav_error.DAVError: (500, 'Concurrent update')

09:21:58.887 - ERROR   : e.src_exception:
None
09:21:58.887 - INFO    : 10.***.***.*** - ***@***.com - [2023-09-08 07:21:58] "PUT /Obsidian/obsidian/_attachments/Dashboard.canvas" length=703, el
ap=1.902sec -> 500 Internal Server Error
```

**Comment by ykorzikowski** [comment]
```
[22:48:22] :) [~/project/obsidian] (main)
ykorzikowski@yksolutions-m1:obsidian $ cat 05_dashboard/Dashboard\ Canvas.canvas
{
	"nodes":[
		{"id":"866b6151fdabf3d0","type":"file","file":"05_dashboard/Dashboard.md","x":-765,"y":-156,"width":1268,"height":585},
		{"id":"2535a23bcaab046d","x":-765,"y":486,"width":1268,"height":777,"type":"file","file":"05_dashboard/Eisenhower Matrix.md"}
	],
	"edges":[]
}[09:39:15] :) [~/project/obsidian] (main)
```

I just synced successfully with a nextcloud instance. I do not think that the file is the issue, I attached it for clearancy. I think its because too many upload tasks causing some concurrency error. 

Maybe for triggering this bug, a python script uploading many foo-bar jsons files to the seafile webdav api will cause this issue?

**Comment by john57165** [comment]
I am getting the same errors when using webdav with the Diarium app.  The Dairium app developer confirmed it was the webdav server not liking concurrent connections. 

```
12:00:43.958 - INFO    : *.*.*.* - ****@***** - [2023-11-17 17:00:43] "PUT /Diarium/v4_Media/0e6c36cd-8d49-432f-8af1-e4d0dc0b32ea" length=234784, elap=3.895sec -> 500 Internal Server Error
12:00:44.108 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 439, in create_empty_resource
    seafile_api.post_empty_file(self.repo.id, self.rel_path, name, self.username)
  File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/seaserv/api.py", line 285, in post_empty_file
    return seafserv_threaded_rpc.post_empty_file(repo_id, parent_dir,
  File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 127, in newfunc
    return fret(ret_str)
  File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 11, in _fret_int
    raise SearpcError(dicts['err_msg'])
pysearpc.common.SearpcError: Concurrent update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/error_printer.py", line 50, in __call__
    for v in app_iter:
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_resolver.py", line 224, in __call__
    for v in app_iter:
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 127, in __call__
    app_iter = provider.custom_request_handler(environ, start_response, method)
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/dav_provider.py", line 1594, in custom_request_handler
    return default_handler(environ, start_response)
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 787, in do_PUT
    res = parentRes.create_empty_resource(util.get_uri_name(path))
  File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 444, in create_empty_resource
    raise DAVError(HTTP_INTERNAL_ERROR, e.msg)
wsgidav.dav_error.DAVError: (500, 'Concurrent update')
```

**Comment by feiniks** [comment]
> I am getting the same errors when using webdav with the Diarium app. The Dairium app developer confirmed it was the webdav server not liking concurrent connections.
> 
> ```
> 12:00:43.958 - INFO    : *.*.*.* - ****@***** - [2023-11-17 17:00:43] "PUT /Diarium/v4_Media/0e6c36cd-8d49-432f-8af1-e4d0dc0b32ea" length=234784, elap=3.895sec -> 500 Internal Server Error
> 12:00:44.108 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
> Traceback (most recent call last):
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 439, in create_empty_resource
>     seafile_api.post_empty_file(self.repo.id, self.rel_path, name, self.username)
>   File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/seaserv/api.py", line 285, in post_empty_file
>     return seafserv_threaded_rpc.post_empty_file(repo_id, parent_dir,
>   File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 127, in newfunc
>     return fret(ret_str)
>   File "/opt/seafile/seafile-server-10.0.1/seafile/lib/python3/site-packages/pysearpc/client.py", line 11, in _fret_int
>     raise SearpcError(dicts['err_msg'])
> pysearpc.common.SearpcError: Concurrent update
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/error_printer.py", line 50, in __call__
>     for v in app_iter:
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_resolver.py", line 224, in __call__
>     for v in app_iter:
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 127, in __call__
>     app_iter = provider.custom_request_handler(environ, start_response, method)
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/dav_provider.py", line 1594, in custom_request_handler
>     return default_handler(environ, start_response)
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/request_server.py", line 787, in do_PUT
>     res = parentRes.create_empty_resource(util.get_uri_name(path))
>   File "/opt/seafile/seafile-server-10.0.1/seahub/thirdpart/wsgidav/seafile_dav_provider.py", line 444, in create_empty_resource
>     raise DAVError(HTTP_INTERNAL_ERROR, e.msg)
> wsgidav.dav_error.DAVError: (500, 'Concurrent update')
> ```

Hi, the concurrent update error is caused by multiple failed attempts to update the database when there are too many concurrent requests.
You can try to upgrade to seafile-server-11.0.1.
11.0 increased the number of retries for concurrent update failures from 3 to 10.
