### ISSUE TITLE
Upgrade from 10.0.1 to 11.0.0 fails with database creation error

### ISSUE THREAD

**Issue by lixmal** [haiwen/seafile#2705]
I was running the image version `10.0.1` from https://hub.docker.com/r/seafileltd/seafile-mc with mysql, LDAP and Oauth configured.

After upgrading to `11.0.0 (beta)` (following https://manual.seafile.com/upgrade/upgrade_docker/) I get the following errors in `seafile-monitor.log`

```
[2023-09-14 19:25:45] Start Monitor 
[2023-09-14 19:25:45] Start seafevents.main 
Failed to create database tables: (pymysql.err.OperationalError) (1044, "Access denied for user 'seafile'@'%' to database 'seahub_db'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:root:Failed create tables, error: Failed to create database tables
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user 'seafile'@'%' to database 'seahub_db'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-11.0.0/pro/python/seafevents/db.py", line 119, in create_db_tables
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/schema.py", line 5792, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3238, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3228, in begin
    with self.connect() as conn:
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/seafile/seafile-server-11.0.0/seahub/thirdpart/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'seafile'@'%' to database 'seahub_db'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-11.0.0/pro/python/seafevents/main.py", line 43, in main
    create_db_tables(config)
  File "/opt/seafile/seafile-server-11.0.0/pro/python/seafevents/db.py", line 122, in create_db_tables
    raise RuntimeError("Failed to create database tables")
RuntimeError: Failed to create database tables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/seafile/seafile-server-11.0.0/pro/python/seafevents/main.py", line 75, in <module>
    main()
  File "/opt/seafile/seafile-server-11.0.0/pro/python/seafevents/main.py", line 47, in main
    raise RuntimeError('Failed create tables, error: %s' % e)
RuntimeError: Failed create tables, error: Failed to create database tables
```

Noteworthy is that it tries to create a database `seahub_db`, while my database is and has always been `seahub-db` (with a dash instead of underscore).

The seafile mysql user doesn't have permissions to create databases, so creation failure is expected.
Is it expected to be able to create another database or does some new code try to normalize `seahub-db` to `seahub_db`?

Both LDAP and OAUTH login fail with `11.0.0`. Rolling back to image tag `10.0.1` makes everything work as before.

**Comment by SkywalkerSpace** [comment]
Thank you for your feedback. We will fix this in the next version.
You can modify the `conf/seafevents.conf ` manually, change the `name` to your seahub database name in the `[DATABASE]` section. And execute `./seafile.sh restart` to restart seafevents.

**Comment by lixmal** [comment]
This seems to be the case already:

```
[DATABASE]
[...]
name = seahub_db
```
