### ISSUE TITLE
11.0.2 pro docker missing boto3 module, fails to import seafevents package

### ISSUE THREAD

**Issue by CursedBlackCat** [haiwen/seafile#2730]
When pulling the pro docker image `11.0.2-testing`, the server fails to start and only gives error 502s. Looking in `seahub.log`, this traceback is present:

```
2024-01-06 00:12:42,780 [ERROR] root:64 <module> Failed to import seafevents package.
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/seahub/utils/__init__.py", line 62, in <module>
    from seafevents import seafevents_api
  File "/opt/seafile/seafile-pro-server-11.0.2/pro/python/seafevents/seafevents_api.py", line 5, in <module>
    from .virus_scanner.db_oper import *
  File "/opt/seafile/seafile-pro-server-11.0.2/pro/python/seafevents/virus_scanner/__init__.py", line 2, in <module>
    from .virus_scan import VirusScan
  File "/opt/seafile/seafile-pro-server-11.0.2/pro/python/seafevents/virus_scanner/virus_scan.py", line 6, in <module>
    from seafobj import commit_mgr, fs_mgr, block_mgr
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/seafobj/__init__.py", line 2, in <module>
    from .commits import commit_mgr
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/seafobj/commits.py", line 67, in <module>
    commit_mgr = SeafCommitManager()
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/seafobj/commits.py", line 26, in __init__
    self.obj_store = objstore_factory.get_obj_store('commits')
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/seafobj/objstore_factory.py", line 362, in get_obj_store
    from seafobj.backends.s3 import SeafObjStoreS3
  File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/seafobj/backends/s3.py", line 1, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

This leads to seahub entirely failing to start, and the server will only refuse connections with error 502 (due to there being no upstream to connect to, as seahub fails to start).

I also went into `gunicorn.conf.py`, set `daemon = False`, and restarted, and here are the logs for that:

```
seafile                | Starting seahub at port 8000 ...
seafile                | Traceback (most recent call last):
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/bin/gunicorn", line 8, in <module>
seafile                |     sys.exit(run())
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 67, in run
seafile                |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/base.py", line 231, in run
seafile                |     super().run()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/base.py", line 72, in run
seafile                |     Arbiter(self).run()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/arbiter.py", line 58, in __init__
seafile                |     self.setup(app)
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/arbiter.py", line 118, in setup
seafile                |     self.app.wsgi()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/base.py", line 67, in wsgi
seafile                |     self.callable = self.load()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 58, in load
seafile                |     return self.load_wsgiapp()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
seafile                |     return util.import_app(self.app_uri)
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/gunicorn/util.py", line 359, in import_app
seafile                |     mod = importlib.import_module(module)
seafile                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
seafile                |     return _bootstrap._gcd_import(name[level:], package, level)
seafile                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
seafile                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
seafile                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
seafile                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
seafile                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
seafile                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/seahub/wsgi.py", line 25, in <module>
seafile                |     application = get_wsgi_application()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/django/core/wsgi.py", line 12, in get_wsgi_application
seafile                |     django.setup(set_prefix=False)
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/django/__init__.py", line 24, in setup
seafile                |     apps.populate(settings.INSTALLED_APPS)
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/django/apps/registry.py", line 116, in populate
seafile                |     app_config.import_models()
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/thirdpart/django/apps/config.py", line 269, in import_models
seafile                |     self.models_module = import_module(models_module_name)
seafile                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
seafile                |     return _bootstrap._gcd_import(name[level:], package, level)
seafile                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
seafile                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
seafile                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
seafile                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
seafile                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
seafile                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/seahub/base/models.py", line 12, in <module>
seafile                |     from seahub.utils import within_time_range, \
seafile                |   File "/opt/seafile/seafile-pro-server-11.0.2/seahub/seahub/utils/__init__.py", line 576, in <module>
seafile                |     SeafEventsSession = seafevents_api.init_db_session_class(parsed_events_conf)
seafile                | AttributeError: 'NoneType' object has no attribute 'init_db_session_class'
seafile                | Error:Seahub failed to start.
seafile                | Please try to run "./seahub.sh start" again
seafile                | Traceback (most recent call last):
seafile                |   File "/scripts/start.py", line 95, in <module>
seafile                |     main()
seafile                |   File "/scripts/start.py", line 81, in main
seafile                |     call('{} start'.format(get_script('seahub.sh')))
seafile                |   File "/scripts/utils.py", line 70, in call
seafile                |     return subprocess.check_call(*a, **kw)
seafile                |   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
seafile                |     raise CalledProcessError(retcode, cmd)
seafile                | subprocess.CalledProcessError: Command '/opt/seafile/seafile-pro-server-11.0.2/seahub.sh start' returned non-zero exit status 1.
```

Downgrading to `latest` fixes this problem, but I am coming here from #2407 where `11.0.2-testing` fixes another breaking issue for me regarding S3 v4 signature mismatches. Thus, using `latest` is not an option in my situation specifically. I understand that `11.0.2-testing` is still a testing version (as the tag name implies) so issues are to be expected, but I thought I would point out this issue that I ran into so that it could be fixed at some point.

**Comment by CursedBlackCat** [comment]
I was able to temporarily work around this by fiddling around with the Docker entrypoint.

I created a new script `/opt/seafile-data/entrypoint.sh`:
```
#! /bin/sh

apt install python3-pip -y
pip3 install boto3

/sbin/my_init -- /scripts/enterpoint.sh

exec "$@"
```

Then in `docker-compose.yml`, I added this under `seafile:`:
```
entrypoint: ["/shared/entrypoint.sh"]
```

This effectively just runs `apt install python3-pip -y` and `pip3 install boto3` before the rest of the container initialization happens, ensuring that the `boto3` package is present. However, of course, this is just a temporary workaround.

**Comment by freeplant** [comment]
It has been fixed in the latest release.

**Comment by MrMohebi** [comment]
It appeared again in version 13.0.12.
docker missing boto3 module
@freeplant can you check it man?

**Comment by Larsvanzijl** [comment]
> It appeared again in version 13.0.12. docker missing boto3 module [@freeplant](https://github.com/freeplant) can you check it man?

Make sure you've got the pro image and not the community edition.
