### ISSUE TITLE
服务没做任何调整，突然访问不了了，查看upgrade_2.0_2.1失败

### ISSUE THREAD

**Issue by blackhumors** [haiwen/seafile#2741]
我在docker中部署的seafile一直正常运行着，我一直没动过，但是最近访问突然访问不到，我看了下docker容器内的报错如下
`[02/25/2024 13:07:08][upgrade]: Running script /opt/seafile/seafile-server-8.0.7/upgrade/upgrade_2.0_2.1.sh

This script would upgrade your seafile server from 2.0 to 2.1
Press [ENTER] to contiune

Can't find a python executable of version 2.6 or above in PATH
Install python 2.6+ before continue.
Or if you installed it in a non-standard PATH, set the PYTHON enviroment varirable to it
[2024-02-25 13:07:08] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[2024-02-25 13:07:08] Running scripts /opt/seafile/seafile-server-8.0.7/upgrade/upgrade_2.0_2.1.sh
Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 58, in main
    check_upgrade()
  File "/scripts/upgrade.py", line 182, in check_upgrade
    run_script_and_update_version_stamp(script, new_version)
  File "/scripts/upgrade.py", line 61, in run_script_and_update_version_stamp
    call(script)
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-8.0.7/upgrade/upgrade_2.0_2.1.sh' returned non-zero exit status 1.`
这是什么原因呢？我应该怎么做

**Comment by blackhumors** [comment]
`root@321c75120cbf:/opt/seafile# which python
/usr/bin/python
root@321c75120cbf:/opt/seafile# python -V
Python 3.8.10
`
容器内python也是没问题的

**Comment by killing** [comment]
Please ask usage or deployment issues on the forum.
