### ISSUE TITLE
Seafile pro 11.0 reporting KeyError ['remember_me'] issue while using two factor backup code

### ISSUE THREAD

**Issue by RedTailBullet** [haiwen/seafile#2810]
The error log is as follows

```
[ERROR] django.request:241 log_response Internal Server Error: /accounts/login/two-factor-auth/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/seahub/two_factor/views/login.py", line 80, in dispatch
    response = super(TwoFactorVerifyView, self).dispatch(request, *a, **kw)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/thirdpart/formtools/wizard/views.py", line 302, in post
    return self.render_done(form, **kwargs)
  File "/opt/seafile/seafile-pro-server-11.0.10/seahub/seahub/two_factor/views/login.py", line 190, in render_done
    kwargs['remember_me'] = form.cleaned_data['remember_me']
KeyError: 'remember_me'
```

It looks like the backup token form does not provide a remember_me field.

**Comment by RedTailBullet** [comment]
oops looks like its the wrong place for a seahub issue. Closed.
