### ISSUE TITLE
Run AppImage on older distributions?

### ISSUE THREAD

**Issue by mailinglists35** [haiwen/seafile#2820]
Hi, is there any chance I can run the linux terminal appimage in some older distros, like FC22?

````
$ ./Seafile-cli-x86_64-9.0.8.AppImage
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/hashlib.py", line 240, in <module>
    func = __get_hash(__func_name)
  File "/usr/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/tmp/.mount_SeafilszE6KR/usr/bin/seaf-cli", line 91, in <module>
    import random
  File "/usr/lib64/python3.4/random.py", line 45, in <module>
    from hashlib import sha512 as _sha512
ImportError: cannot import name 'sha512'
````

$ rpm -qi fuse
Name        : fuse
Version     : 2.9.4
Release     : 3.fc22
Architecture: x86_64

**Comment by mailinglists35** [comment]
this looks like the appimage does not contain the full python3.6 environment but only the app python code while the host is running python 3.4.

**Comment by killing** [comment]
The oldest OS this AppImage can support is Ubuntu 22.04 or Debian 10 or OS around that timeframe. AppImage has dependency on the system libc version. So it's impossible to support very old OS. The cli client doesn't contain Python runtime. Similar to the package-based installation, it uses the system Python runtime.

**Comment by mailinglists35** [comment]
is this an AppImage root issue, or in theory a distributor can choose to package the full python runtime?

**Comment by killing** [comment]
Old versions of OS are always not supported. Even with AppImage, the binaries still requires an up-to-date libc to run. Packaging the entire Python runtime is too heavy.

One solution for you is to change the seaf-cli script inside the package to support Python 3.6. But I'm not sure whether the binary executable (such as seaf-daemon) can run on such an old system.

**Comment by mailinglists35** [comment]
for this case my solution was a different file sync app ;-)
