### ISSUE TITLE
cannot import name 'yield_lines' from 'jaraco.text'

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile#2837]
Upgraded from 9.0.7 to 11.0.12 in one shot.  I ran without any problem the following commands:

```
upgrade_9.0_10.0.sh
upgrade_10.0_11.0.sh
```

On Ubuntu 22.04 LTS, seafile service works, but seahub.sh start` fails with:

```
$ seahub.sh start

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8000 ...

Error happened during creating seafile admin.

Traceback (most recent call last):
  File "/vol/data/base/linux/nodist/x86_64/seafile/seafile-server-11.0.12/seahub/thirdpart/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/vol/data/base/linux/nodist/x86_64/seafile/seafile-server-11.0.12/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/vol/data/base/linux/nodist/x86_64/seafile/seafile-server-11.0.12/seahub/thirdpart/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/vol/data/base/linux/nodist/x86_64/seafile/seafile-server-11.0.12/seahub/thirdpart/gunicorn/util.py", line 25, in <module>
    import pkg_resources
  File "/vol/data/base/linux/nodist/x86_64/seafile/seafile-server-11.0.12/seahub/thirdpart/pkg_resources/__init__.py", line 96, in <module>
    from jaraco.text import (
ImportError: cannot import name 'yield_lines' from 'jaraco.text' (/usr/lib/python3/dist-packages/jaraco/text/__init__.py)
```

I admit, I am surprised by this since I cannot find anybody else having this problem.  I do not understand why I am the only one.

Following are the packages installed on Ubuntu 22.04 LTS.  These are the latest version available for the distribution.  The system is up to date.

```
ii  python3-jaraco.classes                                      3.2.1-3                                                    all          additional routines for obtaining class names
ii  python3-jaraco.collections                                  3.4.0-2                                                    all          models and classes to supplement the stdlib 'collections' module
ii  python3-jaraco.functools                                    3.4.0-2                                                    all          additional functools in the spirit of stdlib's functools
ii  python3-jaraco.itertools                                    2.0.1-5                                                    all          Tools for working with iterables (Python 3)
ii  python3-jaraco.text                                         3.6.0-2                                                    all          jaraco text manipulation functions
```

**Comment by deragon** [comment]
From https://manual.seafile.com/upgrade/upgrade_notes_for_11.0.x/, I now have found:

```
For Ubuntu 20.04/22.04

sudo apt-get update
sudo apt-get install -y python3-dev ldap-utils libldap2-dev

sudo pip3 install future==0.18.* mysqlclient==2.1.* pillow==10.2.* sqlalchemy==2.0.18 captcha==0.5.* django_simple_captcha==0.6.* djangosaml2==1.5.* pysaml2==7.2.* pycryptodome==3.16.* cffi==1.15.1 python-ldap==3.4.3
```

Mmm... I do not like this, as it can break some other stuff on my system.  I will seriously consider upgrading to Ubuntu 24.04 LTS.

**Comment by deragon** [comment]
I believe that seafile server should be packaged also with all of its dependencies...

**Comment by killing** [comment]
The current recommended way is to install with Docker. This can avoid all the dependency issues.

**Comment by deragon** [comment]
I am closing this issue because, yes, Docker is the way, though I have a problems with the Docker installation (I will open other issues).
