### ISSUE TITLE
Cannot create user: "DoesNotExist: User matching query does not exits."

### ISSUE THREAD

**Issue by rominf** [haiwen/seafile#728]
I'm trying to create the user via admin web interface but when I press "Submit" button inside "Add user" window nothing happens.

I've enabled debug (`DEBUG = True`) in `seahub_settings.py` and got following  lines inside `seahub_django_request.log`:
```
2014-07-13 16:52:59,043 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /seafile/useradmin/add/ 
Traceback (most recent call last): 
  File "/srv/seafile/seafile-server-3.0.2/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response 
    response = callback(request, *callback_args, **callback_kwargs) 
  File "/srv/seafile/seafile-server-3.0.2/seahub/seahub/auth/decorators.py", line 25, in _wrapped_view 
    return view_func(request, *args, **kwargs) 
  File "/srv/seafile/seafile-server-3.0.2/seahub/seahub/views/sysadmin.py", line 579, in user_add 
    is_active=True) 
  File "/srv/seafile/seafile-server-3.0.2/seahub/seahub/base/accounts.py", line 35, in create_user 
    return self.get(email=email) 
  File "/srv/seafile/seafile-server-3.0.2/seahub/seahub/base/accounts.py", line 66, in get 
    raise User.DoesNotExist, 'User matching query does not exits.' 
DoesNotExist: User matching query does not exits.
```

I've dumped my `seahub` database:
```bash
pg_dump --data-only --inserts seahub > /tmp/seahub
```
and didn't find (`grep`) any email of the user that I've tried to submit.

Everything else it seems works fine, except user password resetting (seafile sends me new password, but I cannot login with it (wrong password)).. To be on the safe side I've checked database connection with the credentials from the `seahub_settings.py`:
```
$ psql -U seafile -d seahub -h localhost --password
Password for user seafile: 
psql (9.2.7)
Type "help" for help.

seahub=>
```

By the way I'm not using LDAP, seafile users are stored only in the database.

Environment:
```
Linux i 3.11.10-7-desktop #1 SMP PREEMPT Mon Feb 3 09:41:24 UTC 2014 (750023e) x86_64 x86_64 x86_64 GNU/Linux
openSUSE 13.1
seafile 3.0.2
postgresql 9.2.7
```

**Comment by freeplant** [comment]
Has the issue be solved?

**Comment by rominf** [comment]
Nope.
I think that the reason lies in database consistency (#921).

Is there way to start with fresh database saving all files? I know that database contains metainformation: library-user associations, users, shares, etc. Can I recreate this from scratch?

**Comment by riaqn** [comment]
Same problem here. I had a clean install, and just can't add users.
